### ISSUE TITLE
Selecting by year fails (Terzake)

### ISSUE THREAD

**Issue by NofanTasi** [add-ons/plugin.video.vrt.nu#1004]
### Describe the bug ###

Yesterday (Wednesday 3 August) I noticed 'VRT Nu error' when clicking on 'Season 2022' of Terzake.

### To Reproduce ###
1. Go to ... Terzake
2. Click on .... Season 2022
3. Scroll down to .... (nothing)

### Expected behavior ###

The list of Terzake episodes for 2022 should appear.

### Additional context ###

- Operating system: Linux / latest CoreELEC arm
- Kodi version: 19.4
- Addon version: 2.5.12 matrix
- Using a VPN: no
- Country you are using the addon from: ... Belgium

FWIW: same error on x86_64 gentoo linux (same versions)

### Log (if available) ###
```paste below
2022-08-04 18:16:15.863 T:20791    INFO <general>: initializing python engine.
2022-08-04 18:16:16.245 T:20791   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'mso-style-name'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 166, in programs
                                                       VRTPlayer().show_episodes_menu(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 276, in show_episodes_menu
                                                       episode_items, sort, ascending, content = self._apihelper.list_episodes(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 143, in list_episodes
                                                       return self.__map_episodes(episodes, titletype=titletype, season=season, use_favorites=use_favorites, cache_file=cache_file)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 170, in __map_episodes
                                                       list_item, sort, ascending = self.episode_to_listitem(episode, program, cache_file, titletype)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 259, in episode_to_listitem
                                                       info_labels = self._metadata.get_info_labels(episode)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 661, in get_info_labels
                                                       plot=self.get_plot(api_data, season=season),
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 362, in get_plot
                                                       return colour(plot)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 745, in colour
                                                       text = text.format(**COLOUR_THEMES.get(theme))
                                                   KeyError: 'mso-style-name'
                                                   -->End of Python script error report<--
                                                   


```

**Comment by mediaminister** [comment]
Should be fixed.
Test packages.
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.12+matrix.1-seasons-2e8a9b0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9262601/plugin.video.vrt.nu-2.5.12%2Bmatrix.1-seasons-2e8a9b0.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.12-seasons-2e8a9b0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9262602/plugin.video.vrt.nu-2.5.12-seasons-2e8a9b0.zip)

**Comment by NofanTasi** [comment]
thanks for quick fix. note that the description of "03/08 - Terzake 200220803" looks odd (xml).

**Comment by mediaminister** [comment]
I know. The data comes from the VRT NU Search API.
So, VRT NU has to fix this.
