### ISSUE TITLE
GetDirectory - Error

### ISSUE THREAD

**Issue by NofanTasi** [add-ons/plugin.video.vrt.nu#1020]
### To Reproduce ###
1. Go to ... Categories
2. Click on .... News and current affaits
3. Scroll down to .... N/A

### Expected behavior ###

List of programs in category should show

### Additional context ###

- Operating system: Linux CoreELEC
- Kodi version: 19.4
- Addon version: 2.5.14
- Using a VPN: yes/no NO
- Country you are using the addon from: ... Belgium

### Log (if available) ###
```paste below
2022-08-31 18:08:29.654 T:4061    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/categories/nieuws-en-actua
2022-08-31 18:08:29.662 T:3825    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/categories/nieuws-en-actua) failed
2022-08-31 18:08:30.197 T:4068     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-08-31 18:08:31.582 T:4068     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-08-31 18:08:31.591 T:3825    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/) failed
```

**Comment by Bart80-1** [comment]
For what it's worth, same issue when trying to load the favorites.
Log see here: https://paste.kodi.tv/ohugatezim

May I guess: VRT has made some changes and communication is a dirty word ;)

**Comment by davidbe** [comment]
Similar error in the logs for Kodi 18.9.0 on Linux ARM 32-bit and LibreELEC 9.2.8 and latest addon-version since today.

**Comment by mediaminister** [comment]
Yes, loading favorites doesn't work anymore. And today another VRT api stopped working.
I made a workaround so the add-on doesn't crash on the http error.
The workaround is already in the master branch and I'll release this.

**Comment by mediaminister** [comment]
https://github.com/add-ons/plugin.video.vrt.nu/releases

**Comment by NofanTasi** [comment]
thanks @mediaminister for quick fix

**Comment by frankdpGH** [comment]
Maybe some other API issues since VRT max
I did install 2.5.15 but problem remaining : no epg (iptv manager) or VOD for VRT anymore on my Androids environments (Kodi matrix)

2022-08-31 23:00:23.004 T:17954   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module> run(argv)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 355, in run plugin.run(argv)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run self._dispatch(self.path)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch view_func(**kwargs)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 332, in iptv_epg IPTVManager(port).send_epg()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/iptvmanager.py", line 28, in send sock.sendall(json.dumps(func()).encode())  # pylint: disable=not-callable
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/iptvmanager.py", line 59, in send_epg epg_data = TVGuide().get_epg_data()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 276, in get_epg_data video_id, publication_id = self.get_stream_ids(episode_id=episode.get('episodeId'))
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 245, in get_stream_ids video_id = data_json.get('data').get('catalogMember').get('watchAction').get('videoId')
AttributeError: 'NoneType' object has no attribute 'get'
-->End of Python script error report<--
