### ISSUE TITLE
Unable to open VOD (channels, categories, all programs / Tv-guide /... on VRT MAX kodi addon / liveTV works.

### ISSUE THREAD

**Issue by 8OND007** [add-ons/plugin.video.vrt.nu#1082]
### Describe the bug ###

Unable to open any Tv-guide / All programs / categories / channels / VOD /....  
Only liveTV works.

### To Reproduce ###
1. Go to VRT MAX kodi addon
2. Click on All programs OR Categories OR Channels or TV Guide
3. See error (error says to look at log)

### Expected behavior ###

That I can open en view VOD content on VrtMax kodi addon, now it just gives an error.

### Additional context ###

- Operating system: Libreelec (running on Pi4 4GB from USB boot)
- Kodi version: Build 19.4.0 (matrix)
- Addon version: latest 2.5.19-Matrix.1  / WideVine at 4.10.2557.0
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
```paste below
See kodi log on https://paste.kodi.tv/kenakekude

tried to open TV guide / all programs / categories /... below :

2022-12-05 18:46:05.814 T:7270     INFO <general>: initializing python engine.
2022-12-05 18:46:06.221 T:7263     INFO <general>: Python interpreter stopped
2022-12-05 18:46:09.589 T:23614    INFO <general>: Loading skin file: /storage/.kodi/addons/script.kodi.loguploader/resources/skins/default/1080i/script-loguploader-view.xml, load type: LOAD_ON_GUI_INIT
2022-12-05 18:46:31.542 T:7270     INFO <general>: CPythonInvoker(42, /storage/.kodi/addons/script.kodi.loguploader/default.py): script successfully run
2022-12-05 18:46:31.959 T:7270     INFO <general>: Python interpreter stopped
2022-12-05 18:46:44.179 T:7277     INFO <general>: initializing python engine.
2022-12-05 18:46:44.526 T:7277     INFO <general>: CPythonInvoker(43, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:46:55.905 T:7277     INFO <general>: initializing python engine.
2022-12-05 18:46:55.991 T:7277     INFO <general>: CPythonInvoker(43, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:46:57.581 T:7277     INFO <general>: initializing python engine.
2022-12-05 18:46:58.874 T:7277    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: unknown url type: 'None'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 354, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 216, in tvguide
                                                       TVGuide().show_tvguide(date=date, channel=channel)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 51, in show_tvguide
                                                       episode_items = self.get_episode_items(date, channel)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 157, in get_episode_items
                                                       self._favorites.refresh(ttl=ttl('indirect'))
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 40, in refresh
                                                       favorites_dict = self._generate_favorites_dict(self.get_favorites())
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 80, in get_favorites
                                                       access_token = TokenResolver().get_token('vrtnu-site_profile_at')
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 231, in get_token
                                                       token = self._get_new_token(name, variant, roaming=roaming)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 196, in _get_new_token
                                                       return self.login()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 188, in login
                                                       return self._get_new_token(name='vrtnu-site_profile_at', redirect_url=redirect_url)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 204, in _get_new_token
                                                       response = open_url(response.info().get('Location'), headers=headers, follow_redirects=False)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 1101, in open_url
                                                       req = Request(url, headers=headers)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
                                                     File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
                                                     File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
                                                   ValueError: unknown url type: 'None'
                                                   -->End of Python script error report<--
                                                   
2022-12-05 18:46:59.275 T:7277     INFO <general>: Python interpreter stopped
2022-12-05 18:46:59.288 T:7282     INFO <general>: Skipped 2 duplicate messages..
2022-12-05 18:46:59.288 T:7282    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/tvguide/date/yesterday/een
2022-12-05 18:46:59.289 T:23614   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/tvguide/date/yesterday/een) failed
2022-12-05 18:46:59.316 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:46:59.756 T:7284     INFO <general>: CPythonInvoker(44, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:01.588 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:47:01.667 T:7284     INFO <general>: CPythonInvoker(44, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:02.614 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:47:02.695 T:7284     INFO <general>: CPythonInvoker(44, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:10.522 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:47:10.658 T:7284     INFO <general>: CPythonInvoker(44, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:12.046 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:47:12.257 T:7284     INFO <general>: CPythonInvoker(44, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:13.762 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:47:13.957 T:7284     INFO <general>: CPythonInvoker(44, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:15.693 T:7284     INFO <general>: initializing python engine.
2022-12-05 18:47:16.865 T:7284    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: unknown url type: 'None'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 354, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 216, in tvguide
                                                       TVGuide().show_tvguide(date=date, channel=channel)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 51, in show_tvguide
                                                       episode_items = self.get_episode_items(date, channel)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 157, in get_episode_items
                                                       self._favorites.refresh(ttl=ttl('indirect'))
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 40, in refresh
                                                       favorites_dict = self._generate_favorites_dict(self.get_favorites())
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 80, in get_favorites
                                                       access_token = TokenResolver().get_token('vrtnu-site_profile_at')
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 231, in get_token
                                                       token = self._get_new_token(name, variant, roaming=roaming)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 196, in _get_new_token
                                                       return self.login()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 188, in login
                                                       return self._get_new_token(name='vrtnu-site_profile_at', redirect_url=redirect_url)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 204, in _get_new_token
                                                       response = open_url(response.info().get('Location'), headers=headers, follow_redirects=False)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 1101, in open_url
                                                       req = Request(url, headers=headers)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
                                                     File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
                                                     File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
                                                   ValueError: unknown url type: 'None'
                                                   -->End of Python script error report<--
                                                   
2022-12-05 18:47:17.269 T:7284     INFO <general>: Python interpreter stopped
2022-12-05 18:47:17.280 T:7303     INFO <general>: Skipped 6 duplicate messages..
2022-12-05 18:47:17.280 T:7303    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/tvguide/date/yesterday/canvas
2022-12-05 18:47:17.288 T:23614   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/tvguide/date/yesterday/canvas) failed
2022-12-05 18:47:17.308 T:7305     INFO <general>: initializing python engine.
2022-12-05 18:47:17.689 T:7305     INFO <general>: CPythonInvoker(45, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:41.969 T:23637 WARNING <general>: [plugin.video.vrt.nu] Settings changed
2022-12-05 18:47:41.969 T:23637 WARNING <general>: [plugin.video.vrt.nu] Execute: Container.Refresh
2022-12-05 18:47:42.080 T:7305     INFO <general>: initializing python engine.
2022-12-05 18:47:42.089 T:7305  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/tvguide/date/yesterday
2022-12-05 18:47:42.290 T:7305     INFO <general>: CPythonInvoker(45, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:45.062 T:7305     INFO <general>: initializing python engine.
2022-12-05 18:47:45.071 T:7305  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/tvguide/date/yesterday/een
2022-12-05 18:47:45.085 T:7305  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu/sso/login?scope=openid,mid
2022-12-05 18:47:45.630 T:7305  WARNING <general>: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/oidcstate.tkn'.
2022-12-05 18:47:45.638 T:7305  WARNING <general>: [plugin.video.vrt.nu] URL get: https://login.vrt.be/authorize?response_type=code&access_type=offline&client_id=vrtnu-site&scope=openid profile email address video subprofiles mid&redirect_uri=https://www.vrt.be/vrtnu/sso/callback&state=5b395d569577c9daef2c7230c2954fe16494bfa9802b1667d35f93120f5f95371ea7f175e100f13eac6f2a4b8b4b29247a640f40793ebc02fa6859a79cead12804609ec488815ae7924abd4380a4adeca64a94c65ef3adbc1e56a2e9f3352ca0ebbcdace5f508a3b7c7069168fb1579c9cd7ba120f10aca120c84cf7ed894b80121fae6628b3c21b05c989e41275c6d86da732ba9d8de75f3bf50fca9e2aada85f6a03d9bb9d65f2517b230ccd7f3f51e1650ba5ce22d709242c799eb34020b6accdbfe9999a33db79d9f24d6d7bd0eba76ed51e3b4f5eb8ae910928b3cbcab18e404522f19e85d838f7282c3c60f15e8e33e9ff302cf6731f&code_challenge=PDfqDAUgoXen4oafN0dfgIUky_POggh0Ib7WsTQNv9c&code_challenge_method=S256
2022-12-05 18:47:45.855 T:7305  WARNING <general>: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/OIDCXSRF.tkn'.
2022-12-05 18:47:45.857 T:7305  WARNING <general>: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/SESSION.tkn'.
2022-12-05 18:47:45.863 T:7305  WARNING <general>: [plugin.video.vrt.nu] URL post: https://login.vrt.be/perform_login
2022-12-05 18:47:45.863 T:7305  WARNING <general>: [plugin.video.vrt.nu] URL post data: **redacted**
2022-12-05 18:47:46.169 T:7305  WARNING <general>: [plugin.video.vrt.nu] URL get: https://login.vrt.be/authorize?response_type=code&access_type=offline&client_id=vrtnu-site&scope=openid profile email address video subprofiles mid&redirect_uri=https://www.vrt.be/vrtnu/sso/callback&state=5b395d569577c9daef2c7230c2954fe16494bfa9802b1667d35f93120f5f95371ea7f175e100f13eac6f2a4b8b4b29247a640f40793ebc02fa6859a79cead12804609ec488815ae7924abd4380a4adeca64a94c65ef3adbc1e56a2e9f3352ca0ebbcdace5f508a3b7c7069168fb1579c9cd7ba120f10aca120c84cf7ed894b80121fae6628b3c21b05c989e41275c6d86da732ba9d8de75f3bf50fca9e2aada85f6a03d9bb9d65f2517b230ccd7f3f51e1650ba5ce22d709242c799eb34020b6accdbfe9999a33db79d9f24d6d7bd0eba76ed51e3b4f5eb8ae910928b3cbcab18e404522f19e85d838f7282c3c60f15e8e33e9ff302cf6731f&code_challenge=PDfqDAUgoXen4oafN0dfgIUky_POggh0Ib7WsTQNv9c&code_challenge_method=S256
2022-12-05 18:47:46.423 T:7305    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: unknown url type: 'None'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 354, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 216, in tvguide
                                                       TVGuide().show_tvguide(date=date, channel=channel)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 51, in show_tvguide
                                                       episode_items = self.get_episode_items(date, channel)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 157, in get_episode_items
                                                       self._favorites.refresh(ttl=ttl('indirect'))
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 40, in refresh
                                                       favorites_dict = self._generate_favorites_dict(self.get_favorites())
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 80, in get_favorites
                                                       access_token = TokenResolver().get_token('vrtnu-site_profile_at')
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 231, in get_token
                                                       token = self._get_new_token(name, variant, roaming=roaming)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 196, in _get_new_token
                                                       return self.login()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 188, in login
                                                       return self._get_new_token(name='vrtnu-site_profile_at', redirect_url=redirect_url)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 204, in _get_new_token
                                                       response = open_url(response.info().get('Location'), headers=headers, follow_redirects=False)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 1101, in open_url
                                                       req = Request(url, headers=headers)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
                                                     File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
                                                     File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
                                                   ValueError: unknown url type: 'None'
                                                   -->End of Python script error report<--
                                                   
2022-12-05 18:47:46.825 T:7305     INFO <general>: Python interpreter stopped
2022-12-05 18:47:46.830 T:7310     INFO <general>: Skipped 2 duplicate messages..
2022-12-05 18:47:46.830 T:7310    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/tvguide/date/yesterday/een
2022-12-05 18:47:46.855 T:23614   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/tvguide/date/yesterday/een) failed
2022-12-05 18:47:46.874 T:7312     INFO <general>: initializing python engine.
2022-12-05 18:47:47.137 T:7312  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/tvguide/date/yesterday
2022-12-05 18:47:47.289 T:7312     INFO <general>: CPythonInvoker(46, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:50.330 T:7312     INFO <general>: initializing python engine.
2022-12-05 18:47:50.334 T:7312  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/tvguide/date
2022-12-05 18:47:50.417 T:7312     INFO <general>: CPythonInvoker(46, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:51.506 T:7312     INFO <general>: initializing python engine.
2022-12-05 18:47:51.516 T:7312  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/
2022-12-05 18:47:51.587 T:7312     INFO <general>: CPythonInvoker(46, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:47:54.682 T:7312     INFO <general>: initializing python engine.
2022-12-05 18:47:54.692 T:7312  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs
2022-12-05 18:47:54.704 T:7312  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu/sso/login?scope=openid,mid
2022-12-05 18:47:55.136 T:7312  WARNING <general>: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/oidcstate.tkn'.
2022-12-05 18:47:55.140 T:7312  WARNING <general>: [plugin.video.vrt.nu] URL get: https://login.vrt.be/authorize?response_type=code&access_type=offline&client_id=vrtnu-site&scope=openid profile email address video subprofiles mid&redirect_uri=https://www.vrt.be/vrtnu/sso/callback&state=0e0ea4fe9fdff8cb574d64aedfbaccd990b99e9f50a2e4edb9886fa2846031200a0078695f3c36e4a1b485bb336e626b6d15a208220e5c18d36e864454e0dc6ce4b4c5bee7fcbac21e819946d0b0d428dc729cde0ea6ab2f546db803ac1ead63fe3b1c877bef79fee454bc697c13a5c09064db65110dd794b553020e35ab894ccb446c39c9ee0881bd63cc71ee4ee908e352453f553917b2770deef79b216681b0a41d6ce6fe0eee0e5e6c0d98fd1890b9ec738d6da7309775c06ab38060df22fd1cc08d046a80c6d6f195f84b1867b8993e9c59e56a12de42103a7ae25667d45d58906eb12967f46dc3d3644f7204413f12110723bd6d39be&code_challenge=SiaJ7QPCWF0JJrJe8zr_lpZWf6EV476vvcy4QlZ-5ew&code_challenge_method=S256
2022-12-05 18:47:55.331 T:7312  WARNING <general>: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/OIDCXSRF.tkn'.
2022-12-05 18:47:55.334 T:7312  WARNING <general>: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/SESSION.tkn'.
2022-12-05 18:47:55.339 T:7312  WARNING <general>: [plugin.video.vrt.nu] URL post: https://login.vrt.be/perform_login
2022-12-05 18:47:55.339 T:7312  WARNING <general>: [plugin.video.vrt.nu] URL post data: **redacted**
2022-12-05 18:47:55.635 T:7312  WARNING <general>: [plugin.video.vrt.nu] URL get: https://login.vrt.be/authorize?response_type=code&access_type=offline&client_id=vrtnu-site&scope=openid profile email address video subprofiles mid&redirect_uri=https://www.vrt.be/vrtnu/sso/callback&state=0e0ea4fe9fdff8cb574d64aedfbaccd990b99e9f50a2e4edb9886fa2846031200a0078695f3c36e4a1b485bb336e626b6d15a208220e5c18d36e864454e0dc6ce4b4c5bee7fcbac21e819946d0b0d428dc729cde0ea6ab2f546db803ac1ead63fe3b1c877bef79fee454bc697c13a5c09064db65110dd794b553020e35ab894ccb446c39c9ee0881bd63cc71ee4ee908e352453f553917b2770deef79b216681b0a41d6ce6fe0eee0e5e6c0d98fd1890b9ec738d6da7309775c06ab38060df22fd1cc08d046a80c6d6f195f84b1867b8993e9c59e56a12de42103a7ae25667d45d58906eb12967f46dc3d3644f7204413f12110723bd6d39be&code_challenge=SiaJ7QPCWF0JJrJe8zr_lpZWf6EV476vvcy4QlZ-5ew&code_challenge_method=S256
2022-12-05 18:47:55.862 T:7312    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: unknown url type: 'None'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 354, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 156, in programs
                                                       VRTPlayer().show_tvshow_menu()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 198, in show_tvshow_menu
                                                       self._favorites.refresh(ttl=ttl('direct' if use_favorites else 'indirect'))
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 40, in refresh
                                                       favorites_dict = self._generate_favorites_dict(self.get_favorites())
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 80, in get_favorites
                                                       access_token = TokenResolver().get_token('vrtnu-site_profile_at')
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 231, in get_token
                                                       token = self._get_new_token(name, variant, roaming=roaming)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 196, in _get_new_token
                                                       return self.login()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 188, in login
                                                       return self._get_new_token(name='vrtnu-site_profile_at', redirect_url=redirect_url)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 204, in _get_new_token
                                                       response = open_url(response.info().get('Location'), headers=headers, follow_redirects=False)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 1101, in open_url
                                                       req = Request(url, headers=headers)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
                                                     File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
                                                     File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
                                                   ValueError: unknown url type: 'None'
                                                   -->End of Python script error report<--
                                                   
2022-12-05 18:47:56.276 T:7312     INFO <general>: Python interpreter stopped
2022-12-05 18:47:56.289 T:7319     INFO <general>: Skipped 3 duplicate messages..
2022-12-05 18:47:56.289 T:7319    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs
2022-12-05 18:47:56.321 T:23614   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs) failed
2022-12-05 18:47:56.347 T:7321     INFO <general>: initializing python engine.
2022-12-05 18:47:56.573 T:7321  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/
2022-12-05 18:47:56.589 T:7321     INFO <general>: CPythonInvoker(47, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-12-05 18:48:20.484 T:7327     INFO <general>: initializing python engine.
2022-12-05 18:48:20.900 T:7321     INFO <general>: Python interpreter stopped

```

**Comment by mediaminister** [comment]
I can't reproduce.
Please try to login again at https://www.vrt.be/vrtmax/
I guess VRT changed something to the VRT Profile.

Maybe this problem disappears in the add-on afterwards.

**Comment by 8OND007** [comment]
Yep that did the trick :-)
logging in to VRT website from my laptop, I got all kind of popups about customs Ads,....
after setting up my preferences about those ads, i can now see VOD back on my Kodi.
Something to remember if it happens again.

thx

**Comment by mediaminister** [comment]
I added a message dialog in https://github.com/add-ons/plugin.video.vrt.nu/pull/1083 to ask the user to check the VRT account when this happens again.
