### ISSUE TITLE
"VRT MAX fout" when opening "Alle programma's"

### ISSUE THREAD

**Issue by lebeno** [add-ons/plugin.video.vrt.nu#1087]
### Describe the bug ###
Selecting/clicking **Alle programma's** gives popup: **VRT MAX fout**

Error in the log file: `'NoneType' object is not iterable`

This error only occurs when selecting _Alle programma's_. Selecting, browsing and playing via _Categorieën_,  _Binnenkort offline_, _TV-gids_ and live streaming works without issues.

Reboot of system does not resolve this. 

### To Reproduce ###
1. Go to VRT MAX
2. Click on Alle programma's

### Expected behavior ###
I would expect to see a (paged) list of alle programs.

### Additional context ###
- Operating system: Linux, LibreELEC 10.0.2 RPI4.arm
- Kodi version: 19.4.0
- Addon version: 2.5.20+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```
2023-01-04 17:59:02.643 T:1169     INFO <general>: initializing python engine.
2023-01-04 17:59:02.689 T:982      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2023-01-04 17:59:02.699 T:982      INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2023-01-04 17:59:02.702 T:982      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-01-04 17:59:02.703 T:982      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-01-04 17:59:03.531 T:1169     INFO <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2023-01-04 17:59:06.105 T:1169     INFO <general>: initializing python engine.
2023-01-04 17:59:06.293 T:1169     INFO <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2023-01-04 17:59:07.396 T:1169     INFO <general>: initializing python engine.
2023-01-04 17:59:07.628 T:1169     INFO <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2023-01-04 17:59:08.693 T:1169     INFO <general>: initializing python engine.
2023-01-04 17:59:13.762 T:1169     INFO <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2023-01-04 17:59:21.870 T:1169     INFO <general>: initializing python engine.
2023-01-04 17:59:22.079 T:1169    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not iterable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 354, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 156, in programs
                                                       VRTPlayer().show_tvshow_menu()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 204, in show_tvshow_menu
                                                       tvshow_items = get_all_programs()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1070, in get_all_programs
                                                       for program in az_json.get('items'):
                                                   TypeError: 'NoneType' object is not iterable
                                                   -->End of Python script error report<--
                                                   
2023-01-04 17:59:22.670 T:1169     INFO <general>: Python interpreter stopped
2023-01-04 17:59:22.674 T:1367     INFO <general>: Skipped 29 duplicate messages..
2023-01-04 17:59:22.674 T:1367    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs
2023-01-04 17:59:22.692 T:971     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs) failed
2023-01-04 17:59:22.705 T:1369     INFO <general>: initializing python engine.

```

**Comment by mediaminister** [comment]
VRT MAX removed all program items at https://www.vrt.be/vrtnu/a-z/jcr:content/par/glossary.model.json
I'm not sure there is another API to get a list of all programs.

**Comment by mediaminister** [comment]
VRT MAX states it will remove the A-Z list: https://www.vrt.be/vrtnu/a-z/
So I'll remove the All Programs menu item in the VRT MAX add-on

**Comment by dagwieers** [comment]
This is really unfortunate. I do not understand why all of these apps are making it harder to find something. I guess they want to mimic the behaviour of Netflix as much as possible. But the downside is that you get fed what algorithms want you to see, and everything that does not get promoted this way, is not easily discovered. The A-Z listing was very useful for this.
