### ISSUE TITLE
VRT Max - cannot log-in and does not play content where a log-in is needed

### ISSUE THREAD

**Issue by doglover3920** [add-ons/plugin.video.vrt.nu#1118]
### Describe the bug ###
VRT Max does not play from the website.
The Live shows do work.
Probably related to log-in problems.  I get also screens which report that log-in failed.
I am sure my log-in name and password are correct.

### To Reproduce ###
Play some not dutch like Endeavour

### Expected behavior ###
Fix the problem

### Log (if available) ###
2023-07-13 08:24:00.803 T:2616734592   ERROR: [plugin.video.vrt.nu] JSON ValueError: No JSON object could be decoded
2023-07-13 08:24:00.808 T:2616734592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 353, in run
                                                plugin.run(argv)
                                              File "/home/root/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/root/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 155, in programs
                                                VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 249, in show_episodes_menu
                                                episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 977, in get_episodes
                                                api_data = get_seasons(program_name)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1018, in get_seasons
                                                seasons = season_json.get('details').get('data').get('program').get('seasons')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2023-07-13 08:24:01.019 T:2653942656   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/a-world-of-colours--japan
2023-07-13 08:24:01.035 T:3013419904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/a-world-of-colours--japan) failed
2023-07-13 08:24:01.661 T:2616734592   ERROR: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtmax-static/screenshots/een.jpg not found in texture cache
2023-07-13 08:24:07.125 T:2616734592   ERROR: [plugin.video.vrt.nu] JSON ValueError: No JSON object could be decoded
2023-07-13 08:24:07.128 T:2616734592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 353, in run
                                                plugin.run(argv)
                                              File "/home/root/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/root/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 155, in programs
                                                VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 249, in show_episodes_menu
                                                episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 977, in get_episodes
                                                api_data = get_seasons(program_name)
                                              File "/home/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1018, in get_seasons
                                                seasons = season_json.get('details').get('data').get('program').get('seasons')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2023-07-13 08:24:07.358 T:2653942656   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/arcadia
2023-07-13 08:24:07.371 T:3013419904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/arcadia) failed
2023-07-13 08:24:08.055 T:2616734592   ERROR: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtmax-static/screenshots/een.jpg not found in texture cache
2023-07-13 08:24:13.780 T:3013419904 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2023-07-13 08:24:17.680 T:2795692928   ERROR: Could not find suitable input format: application/octet-stream
2023-07-13 08:24:18.528 T:2923426688   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Podium 19.png
2023-07-13 08:24:18.530 T:2795692928   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/VRT NU.png
2023-07-13 08:24:21.613 T:2653942656   ERROR: Unable to find plugin
2023-07-13 08:24:21.613 T:2653942656   ERROR: GetDirectory - Error getting plugin://
2023-07-13 08:24:21.614 T:3013419904   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2023-07-13 08:24:26.387 T:3013419904  NOTICE: Stopping player
2023-07-13 08:24:26.387 T:3013419904  NOTICE: Storing total System Uptime

**Comment by abanink** [comment]
Try my suggestion in [this issue](https://github.com/add-ons/plugin.video.vrt.nu/issues/1117) ?

**Comment by doglover3920** [comment]
Worked as a charm.
Also changed this line:

featured_json = get_url_json('https://www.vrt.be/vrtnu/kijk.model.json')
(line 1042)

**Comment by mediaminister** [comment]
Duplicate of https://github.com/add-ons/plugin.video.vrt.nu/issues/1111
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.23
