### ISSUE TITLE
Film 'Hannah and her sisters' does not play

### ISSUE THREAD

**Issue by NofanTasi** [add-ons/plugin.video.vrt.nu#1119]
### Describe the bug ###

--------
Playback failed
One or more items failed to play. Check log for more
information about this message.
[OK]
--------
appears

see kodi log

### To Reproduce ###
1. Go to ... VRT MAX - Categories 
2. Click on .... Films
3. Scroll down to .... Hannah and her sisters
4. See error when Click on Hannah and her sisters

### Expected behavior ###

Film should play.

Many others do play. Netflix content play as well.

issue might be limited to this film

The film does play on Linux computer in Chrome browser

### Additional context ###

- Operating system: Linux CoreELEC
- Kodi version: 20.2-Nexus
- Addon version: 2.5.23+matrix.1
- Using a VPN: yes/no NO
- Country you are using the addon from: ... Belgium

### Log (if available) ###
```paste below

2023-07-14 14:49:06.010 T:5782  critical <general>: [script.module.inputstreamhelper] ['ldd', '/storage/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2023-07-14 14:49:06.010 T:5782  critical <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2023-07-14 14:49:06.012 T:5782  warning <general>: [script.module.inputstreamhelper] Widevine update check was made on 2023-07-14 14:32
2023-07-14 14:49:06.043 T:3712     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.vrt.nu/play/id/vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f/1688475606781
2023-07-14 14:49:06.050 T:5808     info <general>: Creating InputStream
2023-07-14 14:49:06.093 T:5808  warning <general>: AddOnLog: inputstream.adaptive: Warning "inputstream.adaptive.max_bandwidth" property is deprecated and may not works. Please read "Integration" and "Stream selection types" pages on the Wiki to learn more about the new properties.
2023-07-14 14:49:06.095 T:5808     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 1
2023-07-14 14:49:06.095 T:5808    error <general>: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2023-07-14 14:49:06.428 T:5808    error <general>: AddOnLog: inputstream.adaptive: PreparePaths: URL not valid (https://media-services-public.vrt.be/media-aggregator/v2/media-items/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f$vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/manifest/dash?vrtPlayerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkzNDE0MDAsImdlb0xvY2F0aW9uIjoiQkVMR0lVTSIsImF1dGhlbnRpY2F0ZWQiOnRydWUsInVzZXJTdGF0dXMiOiJWRVJJRklFRF9CRV9SRVNJREVOVCIsImFnZUNhdGVnb3J5IjoiU0lYVEVFTl9QTFVTIiwibWF4UXVhbGl0eSI6IlNEIiwicHJldmlld0FsbG93ZWQiOmZhbHNlLCJkaXNuZXlTZWN1cml0eUxldmVsIjoiQjU3NiJ9.q0j3q55kD8KsyQ2992-HSJMTbFoq3CrLAOKrx-Ka_Rk&client=vrtnu-web%40PROD#.mpd)
2023-07-14 14:49:06.428 T:5808    error <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://media-services-public.vrt.be/media-aggregator/v2/media-items/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f$vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/manifest/dash?vrtPlayerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkzNDE0MDAsImdlb0xvY2F0aW9uIjoiQkVMR0lVTSIsImF1dGhlbnRpY2F0ZWQiOnRydWUsInVzZXJTdGF0dXMiOiJWRVJJRklFRF9CRV9SRVNJREVOVCIsImFnZUNhdGVnb3J5IjoiU0lYVEVFTl9QTFVTIiwibWF4UXVhbGl0eSI6IlNEIiwicHJldmlld0FsbG93ZWQiOmZhbHNlLCJkaXNuZXlTZWN1cml0eUxldmVsIjoiQjU3NiJ9.q0j3q55kD8KsyQ2992-HSJMTbFoq3CrLAOKrx-Ka_Rk&client=vrtnu-web%40PROD#.mpd)
2023-07-14 14:49:06.429 T:5808    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vrt.nu/play/id/vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f/1688475606781]
2023-07-14 14:49:06.429 T:5808     info <general>: CVideoPlayer::OnExit()
2023-07-14 14:49:06.430 T:5808     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2023-07-14 14:49:06.446 T:3712     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-07-14 14:49:06.454 T:3712     info <general>: CVideoPlayer::CloseFile()
2023-07-14 14:49:06.454 T:3712     info <general>: VideoPlayer: waiting for threads to exit
2023-07-14 14:49:06.454 T:3712     info <general>: VideoPlayer: finished waiting
2023-07-14 14:49:07.279 T:4195  critical <general>: [plugin.video.vrt.nu] Timeout: The read operation timed out
                                                   url: https://www.vrt.be/vrtnu-api/graphql/v1
2023-07-14 14:49:07.305 T:4195    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/playerinfo.py", line 76, in onPlayBackStarted
                                                       self.video_id, self.resumepoint_title = get_resumepoint_data(episode_id=self.path.split('/')[-1])
                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 163, in get_resumepoint_data
                                                       video_id = data_json.get('data').get('catalogMember').get('watchAction').get('videoId')
                                                                  ^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-07-14 14:49:26.649 T:5782  critical <general>: [script.module.inputstreamhelper] ['ldd', '/storage/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2023-07-14 14:49:26.650 T:5782  critical <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2023-07-14 14:49:26.651 T:5782  warning <general>: [script.module.inputstreamhelper] Widevine update check was made on 2023-07-14 14:32
2023-07-14 14:49:26.691 T:3712     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.vrt.nu/play/id/vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f/1688475606781
2023-07-14 14:49:26.699 T:5835     info <general>: Creating InputStream
2023-07-14 14:49:26.701 T:5835  warning <general>: AddOnLog: inputstream.adaptive: Warning "inputstream.adaptive.max_bandwidth" property is deprecated and may not works. Please read "Integration" and "Stream selection types" pages on the Wiki to learn more about the new properties.
2023-07-14 14:49:26.704 T:5835     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 1
2023-07-14 14:49:26.704 T:5835    error <general>: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2023-07-14 14:49:26.757 T:5835    error <general>: AddOnLog: inputstream.adaptive: PreparePaths: URL not valid (https://media-services-public.vrt.be/media-aggregator/v2/media-items/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f$vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/manifest/dash?vrtPlayerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkzNDE0MDAsImdlb0xvY2F0aW9uIjoiQkVMR0lVTSIsImF1dGhlbnRpY2F0ZWQiOnRydWUsInVzZXJTdGF0dXMiOiJWRVJJRklFRF9CRV9SRVNJREVOVCIsImFnZUNhdGVnb3J5IjoiU0lYVEVFTl9QTFVTIiwibWF4UXVhbGl0eSI6IlNEIiwicHJldmlld0FsbG93ZWQiOmZhbHNlLCJkaXNuZXlTZWN1cml0eUxldmVsIjoiQjU3NiJ9.q0j3q55kD8KsyQ2992-HSJMTbFoq3CrLAOKrx-Ka_Rk&client=vrtnu-web%40PROD#.mpd)
2023-07-14 14:49:26.757 T:5835    error <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://media-services-public.vrt.be/media-aggregator/v2/media-items/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f$vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/manifest/dash?vrtPlayerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkzNDE0MDAsImdlb0xvY2F0aW9uIjoiQkVMR0lVTSIsImF1dGhlbnRpY2F0ZWQiOnRydWUsInVzZXJTdGF0dXMiOiJWRVJJRklFRF9CRV9SRVNJREVOVCIsImFnZUNhdGVnb3J5IjoiU0lYVEVFTl9QTFVTIiwibWF4UXVhbGl0eSI6IlNEIiwicHJldmlld0FsbG93ZWQiOmZhbHNlLCJkaXNuZXlTZWN1cml0eUxldmVsIjoiQjU3NiJ9.q0j3q55kD8KsyQ2992-HSJMTbFoq3CrLAOKrx-Ka_Rk&client=vrtnu-web%40PROD#.mpd)
2023-07-14 14:49:26.757 T:5835    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vrt.nu/play/id/vid-4a7e7c4a-de07-4549-b8b9-ac708fb2894e/pbs-pub-e290a4bf-378d-4926-85ab-a9f2fa202a3f/1688475606781]
2023-07-14 14:49:26.757 T:5835     info <general>: CVideoPlayer::OnExit()
2023-07-14 14:49:26.758 T:5835     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2023-07-14 14:49:26.830 T:3712     info <general>: CVideoPlayer::CloseFile()
2023-07-14 14:49:26.830 T:3712     info <general>: VideoPlayer: waiting for threads to exit
2023-07-14 14:49:26.830 T:3712     info <general>: VideoPlayer: finished waiting

```

**Comment by mediaminister** [comment]
I made a fix, please test:
Kodi 19/20/21: [plugin.video.vrt.nu-2.5.23+matrix.1-stream-26e60e0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12060950/plugin.video.vrt.nu-2.5.23%2Bmatrix.1-stream-26e60e0.zip)
Kodi 18: [plugin.video.vrt.nu-2.5.23-stream-26e60e0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12060951/plugin.video.vrt.nu-2.5.23-stream-26e60e0.zip)

**Comment by NofanTasi** [comment]
Thanks a lot for fast action. The fix works.
