### ISSUE TITLE
Http error 410: Gone when trying to start program via categories

### ISSUE THREAD

**Issue by bhooyberghs** [add-ons/plugin.video.vrt.nu#1126]
### Describe the bug ###

Http error 410: Gone when trying to start program via categories

### To Reproduce ###
1. Go to Categorieën
2. Click on any category e.g. Nieuws en actua
3. Click on any program e.g. De afspraak

### Expected behavior ###

start playing the program
### Additional context ###

- Operating system: Windows 11 and Libreelec 11.0.1
- Kodi version: Kodi 20.1
- 
- Addon version: 2.5.24 + Matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below
2023-09-12 15:30:57.887 T:2396  critical <general>: [plugin.video.vrt.nu] HTTP Error 410: Gone
2023-09-12 15:30:57.948 T:2396    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\addon.py", line 353, in run
                                                       plugin.run(argv)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\addon.py", line 155, in programs
                                                       VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer.py", line 249, in show_episodes_menu
                                                       episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\api.py", line 977, in get_episodes
                                                       api_data = get_seasons(program_name)
                                                     File "C:\Users\bhooybergh\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\api.py", line 1018, in get_seasons
                                                       seasons = season_json.get('details').get('data').get('program').get('seasons')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-09-12 15:30:58.315 T:13276   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/de-afspraak
2023-09-12 15:30:58.320 T:15600   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/de-afspraak) failed


```

**Comment by on4bam** [comment]
Can confirm. Only livestream works. 
Looks like a json change.

**Comment by on4bam** [comment]
Correction. Livestream is OK and after a program ends it can be started from the TV guide. As long as a program is running it can't be started from the TV-guide.
RPi + Libreelec

**Comment by TScheen** [comment]
I can confirm the issue. 
Matrix on Philips Android TV 7.0.
I can still start a program from TV Guide, but all of my favourites, Het Journaal, Terzake, etc. receive this error message.
Live stream still works.

**Comment by LeEcHeR123** [comment]
I can confirm the issue on Nexus 20.2 Nvidia Shield Pro Android Tv

**Comment by mediaminister** [comment]
I'm working on a fix. (https://github.com/add-ons/plugin.video.vrt.nu/pull/1127)
You can test already an early fix:
Kodi 19/20/21: [plugin.video.vrt.nu-2.5.24+matrix.1-gone-a45a2d8.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12596167/plugin.video.vrt.nu-2.5.24%2Bmatrix.1-gone-a45a2d8.zip)
Kodi 18: [plugin.video.vrt.nu-2.5.24-gone-a45a2d8.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12596166/plugin.video.vrt.nu-2.5.24-gone-a45a2d8.zip)

**Comment by TScheen** [comment]
Just tried the matrix fix, and the bug seems to have gone.
Thx !👍

**Comment by on4bam** [comment]
Just did a quick test.. seems to work again. Thanks for the fast fix.

**Comment by bhooyberghs** [comment]
Can confirm, the fix solved it! Thx !

**Comment by Clyde72** [comment]
Can confirm, issue solved with the fix. RPI 3B+, Kodi 19,5. Thx for the quick fix!

**Comment by LeetaSehmwa** [comment]
Confirmed on an nVidia Shield Pro. Launching individual episodes works (example, from the "Recent" tab), but the action "go to program" to access seasons and episode lists does not (from any starting point).

**Comment by peno64** [comment]
@mediaminister 

The fix doesn't seem to  work for 'Thuis'. The list is empty. It does work for 'het journaal'

**Comment by mediaminister** [comment]
I'm still improving the fix, Thuis is fixed:
Kodi 19/20/21: [plugin.video.vrt.nu-2.5.24+matrix.1-tests-6de34ff.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12601749/plugin.video.vrt.nu-2.5.24%2Bmatrix.1-tests-6de34ff.zip)
Kodi 18: [plugin.video.vrt.nu-2.5.24-tests-6de34ff.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12601751/plugin.video.vrt.nu-2.5.24-tests-6de34ff.zip)

**Comment by peno64** [comment]
@mediaminister great job!

**Comment by mediaminister** [comment]
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.25
