### ISSUE TITLE
error when opening VRT NWS laat

### ISSUE THREAD

**Issue by lebeno** [add-ons/plugin.video.vrt.nu#1136]
Navigating to `Nieuws en actua` and then clicking `VRT NWS laat` immediately shows error: VRT MAX fout. "invalidate cache" option in expert setting does not fix this.

###kodi.log###
```
2023-09-21 23:12:18.102 T:17979   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot unpack non-iterable NoneType object
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 353, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 155, in programs
                                                       VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 249, in show_episodes_menu
                                                       episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: cannot unpack non-iterable NoneType object
                                                   -->End of Python script error report<--
                                                   
2023-09-21 23:12:18.175 T:17977   error <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/vrt-nws-laat
2023-09-21 23:12:18.192 T:970     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/vrt-nws-laat) failed
```
### Additional context ###
- Operating system: LibreElec 11.0.3 on RasPi 4
- Kodi version: 20.2-Nexus
- Addon version: 2.5.25+matrix.1
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
I'm aware the last release didn't fix all problems with the program listings.
I new release is almost ready.
Please test:
Kodi 19/20/21: [plugin.video.vrt.nu-2.5.25+matrix.1-tests-d872bf5.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12700239/plugin.video.vrt.nu-2.5.25%2Bmatrix.1-tests-d872bf5.zip)
Kodi 18: [plugin.video.vrt.nu-2.5.25-tests-d872bf5.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/12700240/plugin.video.vrt.nu-2.5.25-tests-d872bf5.zip)
