### ISSUE TITLE
Categorieen menu doesn't work anymore 

### ISSUE THREAD

**Issue by stijngruwier** [add-ons/plugin.video.vrt.nu#1146]
### Describe the bug ###
the 'Categorieen' menu option does not work anymore.  Instead of listing the categories, a popup shows: "Vrt Max fout controleer log voor meer info."

### To Reproduce ###

1. Go to Categorieen
2. See error

### Expected behavior ###
Able to browse by categorie

### Additional context ###

- Operating system: osmc (vero4k)
- Kodi version: 20.2
- Addon version: 2.5.26+Matrix.1
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###

`2023-12-29 23:33:42.987 T:30017   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 353, in run
                                                       plugin.run(argv)
                                                     File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 164, in categories
                                                       VRTPlayer().show_category_menu(category=category, end_cursor=end_cursor)
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 211, in show_category_menu
                                                       category_items = get_categories()
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1417, in get_categories
                                                       categories_data = get_categories_data()
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1403, in get_categories_data
                                                       categories = get_online_categories()
                                                     File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1611, in get_online_categories
                                                       content_types = find_entry(categories_json.get('data').get('uiSearch'), 'title', 'Aanbod').get('items')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-12-29 23:33:43.105 T:30021   error <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/categories
2023-12-29 23:33:43.125 T:2802    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/categories) failed`

**Comment by mediaminister** [comment]
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.27
I'm waiting to get this release published in official Kodi repo.

**Comment by stijngruwier** [comment]
Super, thanks 👌

**Comment by mediaminister** [comment]
The release is published in official Kodi repo now.
I'm closing this.
