### ISSUE TITLE
HTTP 431: Request entity too large

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#725]
### Describe the bug ###
I just experienced this again. The very long URL (a lot of favorites again) returns an HTTP Error 431.
I thought we already covered this, but apparently we do not cover 431.

```
2020-04-09 15:20:10.824 T:1363145600  NOTICE: [plugin.video.vrt.nu] URL get: https://video-user-data.vrt.be/resume_points
2020-04-09 15:20:11.258 T:1363145600  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2020-04-09 15:20:11.270 T:1363145600  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=[//www.vrt.be/vrtnu/a-z/europa-league/,//www.vrt.be/vrtnu/a-z/ku
lderzipken/,//www.vrt.be/vrtnu/a-z/studio-brussel-interviews/,//www.vrt.be/vrtnu/a-z/hospital--the-westminster-terror-attack/,//www.vrt.be/vrtnu/a-z/de-mia-s/,//www.vrt.be/vrtnu/a-z/de-afspraak-op-vri
jdag/,//www.vrt.be/vrtnu/a-z/weg-van-het-meesterwerk/,//www.vrt.be/vrtnu/a-z/de-noodcentrale/,//www.vrt.be/vrtnu/a-z/ademloos/,//www.vrt.be/vrtnu/a-z/gentbrugge/,//www.vrt.be/vrtnu/a-z/detainment/,//w
ww.vrt.be/vrtnu/a-z/hitler-youth/,//www.vrt.be/vrtnu/a-z/de-collega-s/,//www.vrt.be/vrtnu/a-z/below-the-surface/,//www.vrt.be/vrtnu/a-z/maja/,//www.vrt.be/vrtnu/a-z/darkness--those-who-kill/,//www.vrt
.be/vrtnu/a-z/terzake/,//www.vrt.be/vrtnu/a-z/van-gils-gasten/,//www.vrt.be/vrtnu/a-z/politie-24-7/,//www.vrt.be/vrtnu/a-z/geheimen-van-het-lam-gods/,//www.vrt.be/vrtnu/a-z/baptiste/,//www.vrt.be/vrtn
u/a-z/terzake-docu/,//www.vrt.be/vrtnu/a-z/the-story-of-europe/,//www.vrt.be/vrtnu/a-z/van-a-tot-z-johan-braeckman/,//www.vrt.be/vrtnu/a-z/hun-verhaal-over-down/,//www.vrt.be/vrtnu/a-z/penoza/,//www.v
rt.be/vrtnu/a-z/belpop/,//www.vrt.be/vrtnu/a-z/eenzaam/,//www.vrt.be/vrtnu/a-z/undercover/,//www.vrt.be/vrtnu/a-z/24-hours-in-police-custody/,//www.vrt.be/vrtnu/a-z/de-mooiste-sprookjes-van-grimm/,//w
ww.vrt.be/vrtnu/a-z/de-campus-cup/,//www.vrt.be/vrtnu/a-z/het-huis/,//www.vrt.be/vrtnu/a-z/prettig-gespoord/,//www.vrt.be/vrtnu/a-z/the-korean-war/,//www.vrt.be/vrtnu/a-z/the-reagan-show/,//www.vrt.be
/vrtnu/a-z/unmasking-jihadi-john/,//www.vrt.be/vrtnu/a-z/sporza--de-cup/,//www.vrt.be/vrtnu/a-z/d-day--operation-overlord/,//www.vrt.be/vrtnu/a-z/de-kracht-van-de-leerkracht/,//www.vrt.be/vrtnu/a-z/in
clusief/,//www.vrt.be/vrtnu/a-z/-likeme/,//www.vrt.be/vrtnu/a-z/sporza--volleybal/,//www.vrt.be/vrtnu/a-z/brian-johnson-s-a-life-on-the-road/,//www.vrt.be/vrtnu/a-z/max/,//www.vrt.be/vrtnu/a-z/de-inzi
chten-van/,//www.vrt.be/vrtnu/a-z/the-same-sky/,//www.vrt.be/vrtnu/a-z/war-crimes-dealers/,//www.vrt.be/vrtnu/a-z/sisters/,//www.vrt.be/vrtnu/a-z/kinderen-van-de-kolonie/,//www.vrt.be/vrtnu/a-z/voetba
lmaffia/,//www.vrt.be/vrtnu/a-z/trapped/,//www.vrt.be/vrtnu/a-z/loslopend-wild---gevogelte/,//www.vrt.be/vrtnu/a-z/strafpleiters/,//www.vrt.be/vrtnu/a-z/blood/,//www.vrt.be/vrtnu/a-z/brain-man/,//www.
vrt.be/vrtnu/a-z/marcel-vanthilt-interviewt-iggy-pop/,//www.vrt.be/vrtnu/a-z/zooks/,//www.vrt.be/vrtnu/a-z/notre-dame--in-flames/,//www.vrt.be/vrtnu/a-z/de-verdwijning-van-britta-cloetens/,//www.vrt.b
e/vrtnu/a-z/unite-42/,//www.vrt.be/vrtnu/a-z/kamp-waes/,//www.vrt.be/vrtnu/a-z/the-planets/,//www.vrt.be/vrtnu/a-z/de-warmste-makerspace/,//www.vrt.be/vrtnu/a-z/entre-sol-y-sombra/,//www.vrt.be/vrtnu/
a-z/in-rome/,//www.vrt.be/vrtnu/a-z/the-clinton-affair/,//www.vrt.be/vrtnu/a-z/procureurs/,//www.vrt.be/vrtnu/a-z/mr-bean/,//www.vrt.be/vrtnu/a-z/axel-nort/,//www.vrt.be/vrtnu/a-z/de-twaalf/,//www.vrt
.be/vrtnu/a-z/blue-planet-ii--engelstalig-/,//www.vrt.be/vrtnu/a-z/mamartuile/,//www.vrt.be/vrtnu/a-z/de-regels-van-floor/,//www.vrt.be/vrtnu/a-z/zinzen-en-van-cauwelaert-bij-ivan/,//www.vrt.be/vrtnu/
a-z/the-bay/,//www.vrt.be/vrtnu/a-z/perpetual-grace-ltd/,//www.vrt.be/vrtnu/a-z/stoppeltje/,//www.vrt.be/vrtnu/a-z/is-er-een-dokter-in-de-zaal/,//www.vrt.be/vrtnu/a-z/sporza-hockey/,//www.vrt.be/vrtnu
/a-z/appel-d-urgence/,//www.vrt.be/vrtnu/a-z/still-alice/,//www.vrt.be/vrtnu/a-z/informer/,//www.vrt.be/vrtnu/a-z/de-ideale-wereld/,//www.vrt.be/vrtnu/a-z/studio-ibiza/,//www.vrt.be/vrtnu/a-z/history-
uncovered/,//www.vrt.be/vrtnu/a-z/the-insider--reggie-yates/,//www.vrt.be/vrtnu/a-z/red-velvet/,//www.vrt.be/vrtnu/a-z/the-italian-job/,//www.vrt.be/vrtnu/a-z/alleen-elvis-blijft-bestaan/,//www.vrt.be
/vrtnu/a-z/maigret/,//www.vrt.be/vrtnu/a-z/kosmoo/,//www.vrt.be/vrtnu/a-z/winteruur/,//www.vrt.be/vrtnu/a-z/van-a-tot-z--dirk-de-wachter/,//www.vrt.be/vrtnu/a-z/de-zevende-dag/,//www.vrt.be/vrtnu/a-z/
universiteit-van-vlaanderen/,//www.vrt.be/vrtnu/a-z/twee-tot-de-zesde-macht/,//www.vrt.be/vrtnu/a-z/misdaaddokters/,//www.vrt.be/vrtnu/a-z/circle-of-life/,//www.vrt.be/vrtnu/a-z/de-markt/,//www.vrt.be
/vrtnu/a-z/blue-planet-ii--nederlandstalig-/,//www.vrt.be/vrtnu/a-z/where-the-wild-men-are/,//www.vrt.be/vrtnu/a-z/terug-naar-siberie/,//www.vrt.be/vrtnu/a-z/de-columbus/,//www.vrt.be/vrtnu/a-z/the-fl
atey-enigma/,//www.vrt.be/vrtnu/a-z/tamino--van-de-nieuwe-lichting-tot-rock-werchter/,//www.vrt.be/vrtnu/a-z/paradise-city/,//www.vrt.be/vrtnu/a-z/big-life-fix/,//www.vrt.be/vrtnu/a-z/memoirs-of-an-el
ephant/,//www.vrt.be/vrtnu/a-z/nachtwacht1/,//www.vrt.be/vrtnu/a-z/wereldrecord/,//www.vrt.be/vrtnu/a-z/rookie-cops/,//www.vrt.be/vrtnu/a-z/terzake-extra/,//www.vrt.be/vrtnu/a-z/penguin-central/,//www
.vrt.be/vrtnu/a-z/villa-politica/,//www.vrt.be/vrtnu/a-z/los-zand/,//www.vrt.be/vrtnu/a-z/opgelegd-werk/,//www.vrt.be/vrtnu/a-z/trump-s-trade-war/,//www.vrt.be/vrtnu/a-z/alex/,//www.vrt.be/vrtnu/a-z/i
nside-europe--ten-years-in-turmoil/,//www.vrt.be/vrtnu/a-z/house-of-saud/,//www.vrt.be/vrtnu/a-z/er-was-eens/,//www.vrt.be/vrtnu/a-z/spoed-24-7/,//www.vrt.be/vrtnu/a-z/nick-cave--distant-sky/,//www.vr
t.be/vrtnu/a-z/bloed--zweet---luxeproblemen/,//www.vrt.be/vrtnu/a-z/op-naar-de-100-/,//www.vrt.be/vrtnu/a-z/van-algemeen-nut/,//www.vrt.be/vrtnu/a-z/leaving-neverland/,//www.vrt.be/vrtnu/a-z/papillon/
,//www.vrt.be/vrtnu/a-z/the-trial-of-ratko-mladic/,//www.vrt.be/vrtnu/a-z/icare/,//www.vrt.be/vrtnu/a-z/het-voordeel-van-de-twijfel/,//www.vrt.be/vrtnu/a-z/my-queen-karo/,//www.vrt.be/vrtnu/a-z/geub/,
//www.vrt.be/vrtnu/a-z/zingaburia/,//www.vrt.be/vrtnu/a-z/no-one-saw-a-thing/,//www.vrt.be/vrtnu/a-z/het-peulengaleis/,//www.vrt.be/vrtnu/a-z/lars-is-te-laat/,//www.vrt.be/vrtnu/a-z/therapie/,//www.vr
t.be/vrtnu/a-z/jerusalem--the-making-of-a-holy-city-/,//www.vrt.be/vrtnu/a-z/the-name-of-the-rose/,//www.vrt.be/vrtnu/a-z/zie-mij-graag/,//www.vrt.be/vrtnu/a-z/the-farewell-party/,//www.vrt.be/vrtnu/a
-z/strijd-om-istanbul/,//www.vrt.be/vrtnu/a-z/het-gezin/,//www.vrt.be/vrtnu/a-z/grote-vragen/,//www.vrt.be/vrtnu/a-z/hunters/,//www.vrt.be/vrtnu/a-z/the-family/,//www.vrt.be/vrtnu/a-z/kinderen-van-het
-verzet/,//www.vrt.be/vrtnu/a-z/sharp-objects/,//www.vrt.be/vrtnu/a-z/pano/,//www.vrt.be/vrtnu/a-z/reizen-waes/,//www.vrt.be/vrtnu/a-z/american-history-s-biggest-fibs/,//www.vrt.be/vrtnu/a-z/grensland
ers/,//www.vrt.be/vrtnu/a-z/the-animal/,//www.vrt.be/vrtnu/a-z/tomtesterom/,//www.vrt.be/vrtnu/a-z/corps-diplomatique/,//www.vrt.be/vrtnu/a-z/rock--n--roll-high-school/,//www.vrt.be/vrtnu/a-z/radio-1-
sessies/,//www.vrt.be/vrtnu/a-z/true-romance/,//www.vrt.be/vrtnu/a-z/team-scheire/,//www.vrt.be/vrtnu/a-z/oratorium-zonder-doel/,//www.vrt.be/vrtnu/a-z/earth-from-space/,//www.vrt.be/vrtnu/a-z/down-th
e-road/,//www.vrt.be/vrtnu/a-z/david-attenborough-s-natural-curiosities/,//www.vrt.be/vrtnu/a-z/vrede-op-aarde/,//www.vrt.be/vrtnu/a-z/wat-zegt-de-wetenschap/,//www.vrt.be/vrtnu/a-z/pompidou-xl/,//www
.vrt.be/vrtnu/a-z/picnic-at-hanging-rock/,//www.vrt.be/vrtnu/a-z/sporza--voetbal/,//www.vrt.be/vrtnu/a-z/wissel-van-de-macht/,//www.vrt.be/vrtnu/a-z/belpop-classics/,//www.vrt.be/vrtnu/a-z/killing-eve
/,//www.vrt.be/vrtnu/a-z/kinderen-van-de-collaboratie/,//www.vrt.be/vrtnu/a-z/gr5/,//www.vrt.be/vrtnu/a-z/de-afspraak/,//www.vrt.be/vrtnu/a-z/hooten-and-the-lady/,//www.vrt.be/vrtnu/a-z/wale/,//www.vr
t.be/vrtnu/a-z/country-music/,//www.vrt.be/vrtnu/a-z/behind-closed-doors--through-the-eyes-of-a-child/,//www.vrt.be/vrtnu/a-z/gosal/,//www.vrt.be/vrtnu/a-z/the-loudest-voice/,//www.vrt.be/vrtnu/a-z/th
e-murder-of-sadie-hartley/,//www.vrt.be/vrtnu/a-z/pavarotti--pop-tenor/,//www.vrt.be/vrtnu/a-z/the-dying-detective/,//www.vrt.be/vrtnu/a-z/the-missing/,//www.vrt.be/vrtnu/a-z/rock-werchter/,//www.vrt.
be/vrtnu/a-z/over-water/,//www.vrt.be/vrtnu/a-z/the-handmaid-s-tale/]&from=1&size=80
2020-04-09 15:20:11.590 T:1363145600   ERROR: [plugin.video.vrt.nu] JSON ValueError: No JSON object could be decoded
2020-04-09 15:20:11.604 T:1363145600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 320, in run
                                                plugin.run(argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 109, in favorites_recent
                                                VRTPlayer().show_recent_menu(page=page, use_favorites=True)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 266, in show_recent_menu
                                                episode_items, sort, ascending, content = self._apihelper.list_episodes(page=page, use_favorites=use_favorites, variety='recent')
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 115, in list_episodes
                                                page=page, use_favorites=use_favorites, variety=variety, cache_file=cache_file)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 586, in get_episodes
                                                api_pages = search_json.get('meta').get('pages').get('total')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2020-04-09 15:20:11.846 T:1432351616   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/favorites/recent
2020-04-09 15:20:11.849 T:1937706416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/favorites/recent) failed
2020-04-09 15:20:12.163 T:1363145600  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites
```

### Additional context ###
- Operating system: LibreELEC 9.2.1
- Kodi version: 18.6
- Addon version: 2.3.2
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
I can't remember we ever got HTTP Error 431 in the past, I think we always got HTTP Error 400 in this case: https://github.com/add-ons/plugin.video.vrt.nu/issues/399

Maybe VRT upgraded to a newer version of Elasticsearch that returns more detailed http error messages.
