### ISSUE TITLE
VRT NU add-on fails with HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#748]
### Describe the bug ###
Due to a change at VRT NU on 2020-05-18 at 6:00, the Kodi add-on no longer works with existing VRT NU accounts. It seems the VRT NU website on first login welcomes you and asks to verify your profile information. Once you have done this on the website, your account will work again as expected.

### To Reproduce ###
1. Go to "My favourites" or "All programs"
2. You will get a Kodi error
3. The logs show an HTTP 401 Unauthorized error

### Expected behavior ###
Your existing profile continues to work without issue.

### Additional context ###
- Operating system: LibreELEC v9.2.1
- Kodi version: 18.6
- Addon version: 2.3.2
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
```paste below
2020-05-18 12:02:37.608 T:1383588736  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites
2020-05-18 12:02:37.803 T:1383588736  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginrt.tkn'
2020-05-18 12:02:37.806 T:1383588736  NOTICE: [plugin.video.vrt.nu] URL get: https://token.vrt.be/refreshtoken
2020-05-18 12:02:38.120 T:1383588736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 401: Unauthorized
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 336, in run
                                                plugin.run(argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 79, in favorites_menu
                                                VRTPlayer().show_favorites_menu()
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 120, in show_favorites_menu
                                                self._favorites.refresh(ttl=ttl('indirect'))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 41, in refresh
                                                xvrttoken = TokenResolver().get_xvrttoken(token_variant='user')
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 78, in get_xvrttoken
                                                return self._get_fresh_token(refresh_token, 'X-VRT-Token', token_variant=token_variant)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 262, in _get_fresh_token
                                                opener.open(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 401: Unauthorized
                                            -->End of Python script error report<--
```

**Comment by kheno** [comment]
I was able to fix this issue by opening the android vrtnu app. It asked me to update my vrt user profile. After that the eŕor disappeared.
Hope this helps.

**Comment by tmds** [comment]
@dagwieers The vrtnu addon settings screen is empty for me. Could it be a consequence of this issue?
I tried reinstalling the addon (including clearing settings) but that didn't help.

**Comment by mediaminister** [comment]
> The vrtnu addon settings screen is empty for me.

Looks like a skin problem. Do you use the standard Estuary skin?

> It asked me to update my vrt user profile.

Indeed, everyone needs to update their VRT user profile using the VRT NU Android app or at https://www.vrt.be/vrtnu/
Currently, we cannot integrate registering or managing VRT NU-accounts in the add-on. It's recommended to check the VRT NU website or Android app first when you experience problems with your account in the VRT NU Kodi add-on.

**Comment by tmds** [comment]
> Very strange, this looks like a skin problem. Do you use the standard Estuary skin?

@mediaminister I had set my settings to show only 'basic' settings, which caused nothing to be visible for vrtnu plugin. I changed to a higher level, and now vrtnu plugin settings are visible again.

**Comment by michaelarnauts** [comment]
> > Very strange, this looks like a skin problem. Do you use the standard Estuary skin?
> 
> @mediaminister I had set my settings to show only 'basic' settings, which caused nothing to be visible for vrtnu plugin. I changed to a higher level, and now vrtnu plugin settings are visible again.

Is this in Kodi Leia or Matrix?

**Comment by lebeno** [comment]
I found this issue because I also got the error, but I wonder how many "normal" users will take the same route by checking the logs en then checking github.

Although off-topic, I wonder if a more friendly error message can be popped up that would not need the user checking the logs. Or even better, giving the user a message like "Please log on the VRT NU website and verify your profile information to keep using this KODI plugin".

**Comment by lebeno** [comment]
> I found this issue because I also got the error, but I wonder how many "normal" users will take the same route by checking the logs en then checking github.
> 
> Although off-topic, I wonder if a more friendly error message can be popped up that would not need the user checking the logs. Or even better, giving the user a message like "Please log on the VRT NU website and verify your profile information to keep using this KODI plugin".

Nice, just discovered that there is an effort to "Provide sensible errors on network issues"
https://github.com/add-ons/plugin.video.vrt.nu/pull/385#issuecomment-632373037

**Comment by dagwieers** [comment]
@lenebo Our main problem to have a very specific message for this problem is the lack of user credentials that still suffer from this. But we do want an error-dialog providing a specific error message, together with a hint how to solve it.

And in most cases that would include something like: *Please log on to the VRT NU website with your username/password and see if your problem persists there.*

Which in this case would solve the issue.

**Comment by mediaminister** [comment]
Fixed with https://github.com/add-ons/plugin.video.vrt.nu/pull/762 and https://github.com/add-ons/plugin.video.vrt.nu/pull/790
