### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ghen2** [add-ons/plugin.video.vrt.nu#879]
### Describe the bug ###

When navigating the VRT Nu catalogue, I occasionally get the following backtrace on some programs.
For example currently for "Karrewiet" (Ketnet news show), season 2021  (season 2020 works)

```
2021-04-21 19:57:51.701 T:1206     INFO <general>: initializing python engine.
2021-04-21 19:57:51.705 T:1206  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/karrewiet/2021
2021-04-21 19:57:52.027 T:1206    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: expected string or bytes-like object
                                                   Traceback (most recent call last):
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 360, in run
                                                       plugin.run(argv)
                                                     File "/data/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/data/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 164, in programs
                                                       VRTPlayer().show_episodes_menu(program=program, season=season)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 276, in show_episodes_menu
                                                       episode_items, sort, ascending, content = self._apihelper.list_episodes(program=program, season=season)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 137, in list_episodes
                                                       return self.__map_episodes(episodes, titletype=titletype, season=season, use_favorites=use_favorites, cache_file=cache_file)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 164, in __map_episodes
                                                       list_item, sort, ascending = self.episode_to_listitem(episode, program, cache_file, titletype)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 253, in episode_to_listitem
                                                       info_labels = self._metadata.get_info_labels(episode)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 650, in get_info_labels
                                                       plotoutline=self.get_plotoutline(api_data, season=season),
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 384, in get_plotoutline
                                                       plotoutline = html_to_kodi(api_data.get('subtitle'))
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/utils.py", line 61, in html_to_kodi
                                                       text = key.sub(val, text)
                                                   TypeError: expected string or bytes-like object
                                                   -->End of Python script error report<--
                                                   
2021-04-21 19:57:52.044 T:1206     INFO <general>: Python interpreter stopped
2021-04-21 19:57:52.064 T:1209    ERROR <general>: Skipped 1 duplicate messages..
2021-04-21 19:57:52.064 T:1209    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/karrewiet/2021
2021-04-21 19:57:52.066 T:991     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/karrewiet/2021) failed
2021-04-21 19:57:52.075 T:1211     INFO <general>: initializing python engine.
2021-04-21 19:57:52.132 T:1211  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/karrewiet
2021-04-21 19:57:52.317 T:1211     INFO <general>: CPythonInvoker(11, /data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
```

### To Reproduce ###
In VRT nu catalogue, go to Alle Programma's, select Karrewiet, season 2021.
Merely opening that "folder" triggers the error, not even starting a stream.

### Expected behavior ###
Season 2020 works correctly.
The same show works correctly via VRTNU or Ketnet website:
https://www.vrt.be/vrtnu/a-z/karrewiet/
https://www.ketnet.be/themas/karrewiet

### Additional context ###

- Operating system: Arch Linux x86_64 w/ python 3.9.4
- Kodi version: Kodi 19.0 Matrix
- Addon version: v2.5.1
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
see above

**Comment by mediaminister** [comment]
This is fixed in the master branch already. I'll make a release later tonight.

**Comment by ghen2** [comment]
Confirmed with 2.5.2, thanks!
