### ISSUE TITLE
Timeout: The read operation timed out

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#938]
### Describe the bug ###

It appears we are having these read timeouts quite often lately. It is unclear to me what is causing them, but maybe this is an opportunity to make our code somewhat more robust when this happens.

### To Reproduce ###
Not sure how to reproduce it, we get it quite a lot since very recently.

### Expected behavior ###
We now get a generic Kodi plugin error, whereas I would rather have it show there are issues with the connection, and include the Timeout error "The read operation timed out" as part of it.

### Additional context ###

- Operating system: LibreELEC v10.0.1
- Kodi version: v19.3
- Addon version: v2.5.7+matrix.1
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
```paste below
2022-02-18 23:35:23.087 T:14086    INFO <general>: initializing python engine.
2022-02-18 23:35:23.367 T:14086 WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/
2022-02-18 23:35:23.393 T:14086    INFO <general>: CPythonInvoker(170, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-02-18 23:35:36.436 T:14086    INFO <general>: initializing python engine.
2022-02-18 23:35:36.448 T:14086 WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites
2022-02-18 23:35:36.556 T:14086 WARNING <general>: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginat.tkn'
2022-02-18 23:35:36.564 T:14086 WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu-api/rest/lists/vrtnu-favoritePrograms?tileType=program-poster&tileContentType=program&tileOrientation=po
rtrait&layout=slider&title=Mijn+favoriete+programma's
2022-02-18 23:35:39.311 T:14086   FATAL <general>: [plugin.video.vrt.nu] Timeout: The read operation timed out
                                                   url: https://www.vrt.be/vrtnu-api/rest/lists/vrtnu-favoritePrograms?tileType=program-poster&tileContentType=program&tileOrientation=portrait&layout=slider&title=Mijn+favoriete+programma%27s
2022-02-18 23:35:39.326 T:14086   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in<module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 81, in favorites_menu
                                                       VRTPlayer().show_favorites_menu()
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 125, in show_favorites_menu
                                                       self._favorites.refresh(ttl=ttl('indirect'))
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 40, in refresh
                                                       favorites_dict = self._generate_favorites_dict(self.get_favorites())
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 184, in _generate_favorites_dict
                                                       for item in favorites_json.get(':items', []):
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2022-02-18 23:35:40.018 T:14086    INFO <general>: Python interpreter stopped
2022-02-18 23:35:40.031 T:14090    INFO <general>: Skipped 1 duplicate messages..
2022-02-18 23:35:40.031 T:14090   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/favorites
2022-02-18 23:35:40.035 T:16370   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/favorites) failed
```

**Comment by dagwieers** [comment]
After experiencing this once more (with fix #936) you get the standard error box pointing at a possible network issue. What is strange here is that if I try it a few more times it actually gets past the error fine. It is as if the device has network issues when being idle for some time and the first network-related activity gets a read-timeout. I have only seen this with the VRT NU add-on, but that is no surprise since it is the one I am using the most, and usually the first.

So looking at what is going on, I think we cannot improve it any further, except maybe the following two points:
- Display the actual error message (in this case: "Timeout: The read operation timed out") so that the user has something to work with (or relate to recurring issues)
- We may want to hint to try it again, since it could be a temporary error (which it is in my case)
- Possibly retry the read/download a few times, before giving up (if we could identify what is causing it, we could even test for it)

Also, what surprises me is that I get the Timeout error almost instantly, whereas you would expect to get a Timeout error after some noticeable period of time has passed, so this might be something to investigate as well. Maybe something that can be tweaked from our side ?

**Comment by michaelarnauts** [comment]
Since you get the time-out almost instantly, I'm thinking about a too low timeout value in the code somewhere, like a value in ms instead of seconds or something?

**Comment by mediaminister** [comment]
I'll take a look, since version 2.5.7 a new favorites api is used. VRT deprecated the previous one 
It seems this new api doesn't always return the  favorites data that is requested.
The data is requested with `get_url_json` from kodiutils just like we did before. It guess it's just this new api that behaves differently.

**Comment by screenagerbe** [comment]
Like to bring this up again as we encounter this pretty much daily and now it comes down to whole series not being accessible anymore. My oldest kid wants to watch Karrewiet, but I'm unable to get it playing on kodi.


Below my logs.

```
2025-10-01 20:07:16.241 T:374231    info <general>: -----------------------------------------------------------------------
2025-10-01 20:07:16.241 T:374231    info <general>: Starting Kodi (21.2 (21.2.0) Git:527c7ac02512bd2902a553e350b74ca1794b84aa). Platform: Linux ARM 64-bit
2025-10-01 20:07:16.241 T:374231    info <general>: Using Release Kodi x64
2025-10-01 20:07:16.241 T:374231    info <general>: Kodi compiled 2025-08-13 by GCC 13.2.0 for Linux ARM 64-bit version 6.12.40 (396328)
2025-10-01 20:07:16.241 T:374231    info <general>: Running on LibreELEC (official): 12.2.0, kernel: Linux ARM 64-bit version 6.12.40
2025-10-01 20:07:16.241 T:374231    info <general>: FFmpeg version/source: 6.0.1
2025-10-01 20:07:16.241 T:374231    info <general>: 4 CPU cores available
2025-10-01 20:07:16.241 T:374231    info <general>: ARM Features: Neon enabled
2025-10-01 20:07:16.241 T:374231    info <general>: special://xbmc/ is mapped to: /usr/share/kodi/
2025-10-01 20:07:16.241 T:374231    info <general>: special://xbmcbin/ is mapped to: /usr/lib/kodi
2025-10-01 20:07:16.241 T:374231    info <general>: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2025-10-01 20:07:16.241 T:374231    info <general>: special://masterprofile/ is mapped to: /storage/.kodi/userdata
2025-10-01 20:07:16.241 T:374231    info <general>: special://envhome/ is mapped to: /storage
2025-10-01 20:07:16.241 T:374231    info <general>: special://home/ is mapped to: /storage/.kodi
2025-10-01 20:07:16.241 T:374231    info <general>: special://temp/ is mapped to: /storage/.kodi/temp
2025-10-01 20:07:16.241 T:374231    info <general>: special://logpath/ is mapped to: /storage/.kodi/temp
2025-10-01 20:07:16.241 T:374231    info <general>: Webserver extra whitelist paths: 
2025-10-01 20:07:16.241 T:374231    info <general>: The executable running is: /usr/lib/kodi/kodi.bin
2025-10-01 20:07:16.241 T:374231    info <general>: Local hostname: rpi04-tv
2025-10-01 20:07:16.241 T:374231    info <general>: Log File is located: /storage/.kodi/temp/kodi.log
2025-10-01 20:07:16.241 T:374231    info <general>: -----------------------------------------------------------------------
2025-10-01 20:07:16.242 T:374231    info <general>: loading settings
2025-10-01 20:07:16.242 T:374231    info <general>: special://profile/ is mapped to: special://masterprofile/
2025-10-01 20:07:16.258 T:374231    info <general>: Loaded settings file from special://xbmc/system/advancedsettings.xml
2025-10-01 20:07:16.259 T:374231    info <general>: Contents of special://xbmc/system/advancedsettings.xml are...
                                                   <?xml version="1.0" encoding="utf-8" ?>
                                                   <advancedsettings version="1.0">
                                                     <gputempcommand>/usr/bin/gputemp</gputempcommand>
                                                     <showexitbutton>false</showexitbutton>
                                                     <remotedelay>1</remotedelay>
                                                     <fanartres>720</fanartres>
                                                     <imageres>540</imageres>
                                                   </advancedsettings>
                                                   
2025-10-01 20:07:16.259 T:374231    info <general>: No settings file to load (special://masterprofile/advancedsettings.xml)
2025-10-01 20:07:16.259 T:374231    info <general>: Default Video Player: VideoPlayer
2025-10-01 20:07:16.259 T:374231    info <general>: Default Audio Player: paplayer
2025-10-01 20:07:16.259 T:374231    info <general>: Disabled debug logging due to GUI setting. Level 0.
2025-10-01 20:07:16.259 T:374231    info <general>: Log level changed to "info"
2025-10-01 20:07:16.259 T:374231    info <general>: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
2025-10-01 20:07:16.266 T:374231    info <general>: New Cache GUI Settings (replacement of cache in advancedsettings.xml) are:
                                                     Buffer Mode: 4
                                                     Memory Size: 20 MB
                                                     Read Factor: 4.00 x 
                                                     Chunk Size : 131072 bytes
2025-10-01 20:07:16.266 T:374231    info <general>: creating subdirectories
2025-10-01 20:07:16.266 T:374231    info <general>: userdata folder: special://masterprofile/
2025-10-01 20:07:16.266 T:374231    info <general>: recording folder: 
2025-10-01 20:07:16.266 T:374231    info <general>: screenshots folder: /storage/screenshots/
2025-10-01 20:07:16.270 T:374231    info <general>: Running database version Addons33
```

```
2025-10-03 20:03:59.629 T:887498 warning <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/karrewiet/2024
2025-10-03 20:03:59.631 T:887498 warning <general>: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtnusite_profile_at.tkn'
2025-10-03 20:03:59.633 T:887498 warning <general>: [plugin.video.vrt.nu] URL post: https://www.vrt.be/vrtnu-api/graphql/v1
2025-10-03 20:03:59.634 T:887498 warning <general>: [plugin.video.vrt.nu] URL post data: b'{"operationName": "TileList", "query": "\\n        query TileList(\\n          $listId: ID!\\n          $sort: SortInput\\n          $lazyItemCount: Int = 20\\n          $after: ID\\n          $before: ID\\n        ) {\\n          list(listId: $listId, sort: $sort) {\\n            __typename\\n            ... on PaginatedTileList {\\n              ...paginatedTileListFragment\\n              __typename\\n            }\\n            ... on StaticTileList {\\n              ...staticTileListFragment\\n              __typename\\n            }\\n          }\\n        }\\n        fragment staticTileListFragment on StaticTileList {\\n          __typename\\n          objectId\\n          listId\\n          title\\n          description\\n          tileContentType\\n          displayType\\n          maxAge\\n          tileVariant\\n          sort {\\n            icon\\n            order\\n            title\\n            __typename\\n          }\\n          action {\\n            ... on LinkAction {\\n              __typename\\n              externalTarget\\n              link\\n            }\\n            ... on SwitchTabAction {\\n              __typename\\n              link\\n              referencedTabId\\n            }\\n            __typename\\n          }\\n          banner {\\n            actionItems {\\n              ...actionItemFragment\\n              __typename\\n            }\\n            description\\n            image {\\n              ...imageFragment\\n              __typename\\n            }\\n            compactLayout\\n            backgroundColor\\n            textTheme\\n            title\\n            titleArt {\\n              objectId\\n              templateUrl\\n              __typename\\n            }\\n            __typename\\n          }\\n          bannerSize\\n          items {\\n            ...tileFragment\\n            __typename\\n          }\\n          paginatedItems(first: $lazyItemCount, after: $after, before: $before) {\\n            __typename\\n            edges {\\n              __typename\\n              cursor\\n              node {\\n                __typename\\n                ...tileFragment\\n              }\\n            }\\n            pageInfo {\\n              __typename\\n              endCursor\\n              hasNextPage\\n              hasPreviousPage\\n              startCursor\\n            }\\n          }\\n          ... on IComponent {\\n            ...componentTrackingDataFragment\\n            __typename\\n          }\\n        }\\n        fragment actionItemFragment on ActionItem {\\n          __typename\\n          objectId\\n          accessibilityLabel\\n          active\\n          mode\\n          title\\n          themeOverride\\n          action {\\n            ...actionFragment\\n            __typename\\n          }\\n          icons {\\n            ...iconFragment\\n            __typename\\n          }\\n        }\\n        fragment actionFragment on Action {\\n          __typename\\n          ... on FavoriteAction {\\n            id\\n            favorite\\n            title\\n            __typename\\n          }\\n          ... on ListDeleteAction {\\n            listName\\n            id\\n            listId\\n            title\\n            __typename\\n          }\\n          ... on ListTileDeletedAction {\\n            listName\\n            id\\n            listId\\n            __typename\\n          }\\n          ... on LinkAction {\\n            internalTarget\\n            link\\n            internalTarget\\n            externalTarget\\n            passUserIdentity\\n            zone {\\n              preferredZone\\n              isExclusive\\n              __typename\\n            }\\n            linkTokens {\\n              __typename\\n              placeholder\\n              value\\n            }\\n            __typename\\n          }\\n          ... on ClientDrivenAction {\\n            __typename\\n            clientDrivenActionType\\n          }\\n          ... on ShareAction {\\n            title\\n            url\\n            __typename\\n          }\\n          ... on SwitchTabAction {\\n            referencedTabId\\n            link\\n            __typename\\n          }\\n          ... on FinishAction {\\n            id\\n            __typename\\n          }\\n        }\\n        fragment iconFragment on Icon {\\n          __typename\\n          accessibilityLabel\\n          position\\n          ... on DesignSystemIcon {\\n            value {\\n              name\\n              __typename\\n            }\\n            activeValue {\\n              name\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on ImageIcon {\\n            value {\\n              srcSet {\\n                src\\n                format\\n                __typename\\n              }\\n              __typename\\n            }\\n            activeValue {\\n              srcSet {\\n                src\\n                format\\n                __typename\\n              }\\n              __typename\\n            }\\n            __typename\\n          }\\n        }\\n        fragment componentTrackingDataFragment on IComponent {\\n          trackingData {\\n            data\\n            perTrigger {\\n              trigger\\n              data\\n              template {\\n                id\\n                __typename\\n              }\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        fragment imageFragment on Image {\\n          __typename\\n          objectId\\n          alt\\n          focusPoint {\\n            x\\n            y\\n            __typename\\n          }\\n          templateUrl\\n        }\\n        fragment tileFragment on Tile {\\n          ... on IIdentifiable {\\n            __typename\\n            objectId\\n          }\\n          ... on IComponent {\\n            ...componentTrackingDataFragment\\n            __typename\\n          }\\n          ... on ITile {\\n            title\\n            active\\n            accessibilityTitle\\n            action {\\n              __typename\\n              ... on LinkAction {\\n                internalTarget\\n                link\\n                internalTarget\\n                externalTarget\\n                __typename\\n              }\\n            }\\n            actionItems {\\n              ...actionItemFragment\\n              __typename\\n            }\\n            image {\\n              ...imageFragment\\n              __typename\\n            }\\n            primaryMeta {\\n              ...metaFragment\\n              __typename\\n            }\\n            secondaryMeta {\\n              ...metaFragment\\n              __typename\\n            }\\n            tertiaryMeta {\\n              ...metaFragment\\n              __typename\\n            }\\n            indexMeta {\\n              __typename\\n              type\\n              value\\n            }\\n            statusMeta {\\n              __typename\\n              type\\n              value\\n            }\\n            labelMeta {\\n              __typename\\n              type\\n              value\\n            }\\n            __typename\\n          }\\n          ... on ContentTile {\\n            brand\\n            brandLogos {\\n              ...brandLogosFragment\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on BannerTile {\\n            backgroundColor\\n            brand\\n            brandLogos {\\n              ...brandLogosFragment\\n              __typename\\n            }\\n            compactLayout\\n            description\\n            textTheme\\n            titleArt {\\n              objectId\\n              templateUrl\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on EpisodeTile {\\n            description\\n            available\\n            chapterStart\\n            progress {\\n              completed\\n              progressInSeconds\\n              durationInSeconds\\n              __typename\\n            }\\n            episode {\\n              __typename\\n              id\\n              name\\n              available\\n              whatsonId\\n              title\\n              description\\n              subtitle\\n              permalink\\n              logo\\n              brand\\n              brandLogos {\\n                type\\n                mono\\n                primary\\n              }\\n              image {\\n                alt\\n                templateUrl\\n              }\\n\\n              ageRaw\\n              ageValue\\n\\n              durationRaw\\n              durationValue\\n              durationSeconds\\n\\n              episodeNumberRaw\\n              episodeNumberValue\\n              episodeNumberShortValue\\n\\n              onTimeRaw\\n              onTimeValue\\n              onTimeShortValue\\n\\n              offTimeRaw\\n              offTimeValue\\n              offTimeShortValue\\n\\n              productPlacementValue\\n              productPlacementShortValue\\n\\n              regionRaw\\n              regionValue\\n              program {\\n                title\\n                id\\n                link\\n                programType\\n                description\\n                shortDescription\\n                subtitle\\n                announcementType\\n                announcementValue\\n                whatsonId\\n                image {\\n                  alt\\n                  templateUrl\\n                }\\n                posterImage {\\n                  alt\\n                  templateUrl\\n                }\\n              }\\n              season {\\n                id\\n                titleRaw\\n                titleValue\\n                titleShortValue\\n              }\\n              analytics {\\n                airDate\\n                categories\\n                contentBrand\\n                episode\\n                mediaSubtype\\n                mediaType\\n                name\\n                pageName\\n                season\\n                show\\n              }\\n              primaryMeta {\\n                longValue\\n                shortValue\\n                type\\n                value\\n                __typename\\n              }\\n              secondaryMeta {\\n                longValue\\n                shortValue\\n                type\\n                value\\n                __typename\\n              }\\n              watchAction {\\n                avodUrl\\n                completed\\n                resumePoint\\n                resumePointTotal\\n                resumePointProgress\\n                resumePointTitle\\n                episodeId\\n                videoId\\n                publicationId\\n                streamId\\n              }\\n              favoriteAction {\\n                favorite\\n                id\\n                title\\n              }\\n            }\\n            __typename\\n          }\\n          ... on ProgramTile {\\n            __typename\\n            objectId\\n            id\\n            link\\n            tileType\\n            image {\\n              alt\\n              templateUrl\\n            }\\n            title\\n            program {\\n              title\\n              id\\n              link\\n              programType\\n              description\\n              shortDescription\\n              subtitle\\n              announcementType\\n              announcementValue\\n              whatsonId\\n              image {\\n                alt\\n                templateUrl\\n              }\\n              posterImage {\\n                alt\\n                templateUrl\\n              }\\n              favoriteAction {\\n                favorite\\n                id\\n                title\\n              }\\n            }\\n          }\\n          ... on PodcastEpisodeTile {\\n            available\\n            description\\n            progress {\\n              completed\\n              progressInSeconds\\n              durationInSeconds\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on AudioLivestreamTile {\\n            brand\\n            brandsLogos {\\n              brand\\n              brandTitle\\n              logos {\\n                ...brandLogosFragment\\n                __typename\\n              }\\n              __typename\\n            }\\n            progress {\\n              durationInSeconds\\n              progressInSeconds\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on LivestreamTile {\\n            description\\n            progress {\\n              durationInSeconds\\n              progressInSeconds\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on ButtonTile {\\n            mode\\n            icons {\\n              ...iconFragment\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on RadioEpisodeTile {\\n            available\\n            description\\n            progress {\\n              completed\\n              progressInSeconds\\n              durationInSeconds\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on RadioFragmentTile {\\n            progress {\\n              completed\\n              progressInSeconds\\n              durationInSeconds\\n              __typename\\n            }\\n            __typename\\n          }\\n          ... on SongTile {\\n            startDate\\n            formattedStartDate\\n            endDate\\n            description\\n            __typename\\n          }\\n          __typename\\n        }\\n        fragment brandLogosFragment on Logo {\\n          colorOnColor\\n          height\\n          mono\\n          primary\\n          type\\n          width\\n          __typename\\n        }\\n        fragment metaFragment on MetaDataItem {\\n          __typename\\n          type\\n          value\\n          shortValue\\n          longValue\\n        }\\n        fragment paginatedTileListFragment on PaginatedTileList {\\n          __typename\\n          objectId\\n          listId\\n          action {\\n            ... on LinkAction {\\n              __typename\\n              externalTarget\\n              link\\n            }\\n            ... on SwitchTabAction {\\n              __typename\\n              link\\n              referencedTabId\\n            }\\n            __typename\\n          }\\n          banner {\\n            actionItems {\\n              ...actionItemFragment\\n              __typename\\n            }\\n            backgroundColor\\n            compactLayout\\n            description\\n            image {\\n              ...imageFragment\\n              __typename\\n            }\\n            titleArt {\\n              ...imageFragment\\n              __typename\\n            }\\n            textTheme\\n            title\\n            __typename\\n          }\\n          bannerSize\\n          displayType\\n          maxAge\\n          tileVariant\\n          paginatedItems(first: $lazyItemCount, after: $after, before: $before) {\\n            __typename\\n            edges {\\n              __typename\\n              cursor\\n              node {\\n                __typename\\n                ...tileFragment\\n              }\\n            }\\n            pageInfo {\\n              __typename\\n              endCursor\\n              hasNextPage\\n              hasPreviousPage\\n              startCursor\\n            }\\n          }\\n          sort {\\n            icon\\n            order\\n            title\\n            __typename\\n          }\\n          tileContentType\\n          title\\n          description\\n          ... on IComponent {\\n            ...componentTrackingDataFragment\\n            __typename\\n          }\\n        }\\n    ", "variables": {"listId": "static:/vrtnu/a-z/karrewiet/2024.episodes-list.json", "after": "", "lazyItemCount": 80}}'
2025-10-03 20:04:02.154 T:887498 critical <general>: [plugin.video.vrt.nu] Timeout: The read operation timed out
                                                   url: https://www.vrt.be/vrtnu-api/graphql/v1
2025-10-03 20:04:02.190 T:887498   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 13, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 320, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 122, in programs
                                                       VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 213, in show_episodes_menu
                                                       episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1884, in get_episodes
                                                       paginated = api_data.get('data', {}).get('list', {}).get('paginatedItems', {})
                                                                   ^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2025-10-03 20:04:02.293 T:887500   error <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/karrewiet/2024
2025-10-03 20:04:02.321 T:374231   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/karrewiet/2024) failed
2025-10-03 20:04:02.548 T:887503 warning <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/karrewiet
2025-10-03 20:04:02.601 T:887503 warning <general>: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtnusite_profile_at.tkn'
2025-10-03 20:04:02.605 T:887503 warning <general>: [plugin.video.vrt.nu] URL post: https://www.vrt.be/vrtnu-api/graphql/v1
2025-10-03 20:04:02.605 T:887503 warning <general>: [plugin.video.vrt.nu] URL post data: b'{"operationName": "VideoProgramPage", "query": "\\n        query VideoProgramPage(\\n          $pageId: ID!) {\\n          page(id: $pageId) {\\n            ... on ProgramPage {\\n              id\\n              permalink\\n              components {\\n                __typename\\n                ... on PageHeader {\\n                  mostRelevantEpisodeTile {\\n                    __typename\\n                    title\\n                    tile {\\n                      ...episodeTile\\n                      __typename\\n                    }\\n                    __typename\\n                  }\\n                  __typename\\n                }\\n                ... on PaginatedTileList {\\n                  __typename\\n                  id: objectId\\n                  objectId\\n                  listId\\n                  title\\n                  tileContentType\\n                }\\n                ... on ContainerNavigation {\\n                  id: objectId\\n                  navigationType\\n                  items {\\n                    id: objectId\\n                    title\\n                    active\\n                    components {\\n                      __typename\\n                      ... on PaginatedTileList {\\n                        __typename\\n                        id: objectId\\n                        objectId\\n                        listId\\n                        title\\n                        tileContentType\\n                      }\\n                      ... on StaticTileList {\\n                        __typename\\n                        id: objectId\\n                        objectId\\n                        listId\\n                        title\\n                        tileContentType\\n                      }\\n                      ... on LazyTileList {\\n                        __typename\\n                        id: objectId\\n                        objectId\\n                        listId\\n                        title\\n                        tileContentType\\n                      }\\n                      ... on IComponent {\\n                        ... on ContainerNavigation {\\n                          id: objectId\\n                          navigationType\\n                          items {\\n                            id: objectId\\n                            title\\n                            components {\\n                              __typename\\n                              ... on Component {\\n                                ... on PaginatedTileList {\\n                                  __typename\\n                                  id: objectId\\n                                  objectId\\n                                  listId\\n                                  title\\n                                  tileContentType\\n                                }\\n                                ... on StaticTileList {\\n                                  __typename\\n                                  id: objectId\\n                                  objectId\\n                                  listId\\n                                  title\\n                                  tileContentType\\n                                }\\n                                ... on LazyTileList {\\n                                  __typename\\n                                  id: objectId\\n                                  objectId\\n                                  listId\\n                                  title\\n                                  tileContentType\\n                                }\\n                                __typename\\n                              }\\n                            }\\n                            __typename\\n                          }\\n                          __typename\\n                        }\\n                        __typename\\n                      }\\n                    }\\n                    __typename\\n                  }\\n                  __typename\\n                }\\n                __typename\\n              }\\n              __typename\\n            }\\n            __typename\\n          }\\n        }\\n        \\n    fragment episodeTile on EpisodeTile {\\n      __typename\\n      id\\n      title\\n      episode {\\n        __typename\\n        id\\n        name\\n        available\\n        whatsonId\\n        title\\n        description\\n        subtitle\\n        permalink\\n        logo\\n        brand\\n        brandLogos {\\n          type\\n          mono\\n          primary\\n        }\\n        image {\\n          alt\\n          templateUrl\\n        }\\n\\n        ageRaw\\n        ageValue\\n\\n        durationRaw\\n        durationValue\\n        durationSeconds\\n\\n        episodeNumberRaw\\n        episodeNumberValue\\n        episodeNumberShortValue\\n\\n        onTimeRaw\\n        onTimeValue\\n        onTimeShortValue\\n\\n        offTimeRaw\\n        offTimeValue\\n        offTimeShortValue\\n\\n        productPlacementValue\\n        productPlacementShortValue\\n\\n        regionRaw\\n        regionValue\\n        program {\\n          title\\n          id\\n          link\\n          programType\\n          description\\n          shortDescription\\n          subtitle\\n          announcementType\\n          announcementValue\\n          whatsonId\\n          image {\\n            alt\\n            templateUrl\\n          }\\n          posterImage {\\n            alt\\n            templateUrl\\n          }\\n        }\\n        season {\\n          id\\n          titleRaw\\n          titleValue\\n          titleShortValue\\n        }\\n        analytics {\\n          airDate\\n          categories\\n          contentBrand\\n          episode\\n          mediaSubtype\\n          mediaType\\n          name\\n          pageName\\n          season\\n          show\\n        }\\n        primaryMeta {\\n          longValue\\n          shortValue\\n          type\\n          value\\n          __typename\\n        }\\n        secondaryMeta {\\n          longValue\\n          shortValue\\n          type\\n          value\\n          __typename\\n        }\\n        watchAction {\\n          avodUrl\\n          completed\\n          resumePoint\\n          resumePointTotal\\n          resumePointProgress\\n          resumePointTitle\\n          episodeId\\n          videoId\\n          publicationId\\n          streamId\\n        }\\n        favoriteAction {\\n          favorite\\n          id\\n          title\\n        }\\n      }\\n    }\\n\\n    ", "variables": {"pageId": "/vrtnu/a-z/karrewiet.model.json"}}'
2025-10-03 20:04:02.822 T:887503 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
```

**Comment by mediaminister** [comment]
I guess this is related to high latency or packet loss on your connection. The moment you experience this, you should immediately test if it works on a different ISP.

All "The read operation timed out" errors in this issue come from customers of the same ISP right?

**Comment by screenagerbe** [comment]
> All "The read operation timed out" errors in this issue are reported by customers of the same ISP right? I guess some DOCSIS ISP which is famous for packet loss and latency spikes during prime time.

Afraid I'm in a TINA situation in this until some ISP brings FttH here 🥴

**Comment by mediaminister** [comment]
There is no 4G network to test? No VDSL? Really?

**Comment by mediaminister** [comment]
I guess I found the problem with long episode lists like "Karrewiet Nieuwsvideos > België"
When requesting 300 items at once (Add-on Settings > Interface > Number of items per page) I get a HTTP Error 500: Internal Server Error from VRT MAX API after 9 seconds.

I guess the timeout error you get is something that is related to the LibreELEC settings. You shouldn't get a timeout error, the normal behavior should be a http error.

The main problem is that the VRT MAX API is apparently not designed to serve a long episode list in real time.
A list of the default page size of 50 items takes already 5.5 seconds which is really bad.
