### ISSUE TITLE
VRT Nu episodes of series do not start

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.vrt.nu#949]
### Describe the bug ###
On VRT Nu episodes of series do not start, movies seem to play.

### To Reproduce ###
1. Go to VRT.Nu favorites
2. Click on Dwars door de lage landen
3. Start episode

### Expected behavior ###
Episode starts

### Additional context ###

- Operating system: LibreElec 10.0.1
- Kodi version: 19.3 matrix
- Addon version: 2.5.8
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
```
2022-04-20 20:39:21.123 T:884      INFO <general>: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-04-20 20:39:25.787 T:884      INFO <general>: initializing python engine.
2022-04-20 20:39:26.310 T:818      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-04-20 20:39:35.961 T:884     FATAL <general>: [plugin.video.vrt.nu] HTTP Error 503: Service Unavailable
2022-04-20 20:39:36.067 T:884     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 166, in programs
                                                       VRTPlayer().show_episodes_menu(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 276, in show_episodes_menu
                                                       episode_items, sort, ascending, content = self._apihelper.list_episodes(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 129, in list_episodes
                                                       episodes = self.get_episodes(program=program, season=season, category=category, feature=feature, programtype=programtype,
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 641, in get_episodes
                                                       api_pages = search_json.get('meta').get('pages').get('total')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2022-04-20 20:39:36.403 T:884      INFO <general>: Python interpreter stopped
2022-04-20 20:39:36.409 T:888      INFO <general>: Skipped 1 duplicate messages..
2022-04-20 20:39:36.409 T:888     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/dwars-door-de-lage-landen
2022-04-20 20:39:36.431 T:818     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/dwars-door-de-lage-landen) failed
2022-04-20 20:39:57.699 T:892      INFO <general>: initializing python engine.
2022-04-20 20:39:58.107 T:892      INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-04-20 20:39:58.178 T:892      INFO <general>: initializing python engine.
2022-04-20 20:39:58.364 T:892      INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-04-20 20:40:02.400 T:892      INFO <general>: initializing python engine.
2022-04-20 20:40:02.560 T:892      INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-04-20 20:40:04.019 T:892      INFO <general>: initializing python engine.
2022-04-20 20:40:04.531 T:892   WARNING <general>: Invalid media type ""
2022-04-20 20:40:04.627 T:892      INFO <general>: Skipped 5 duplicate messages..
2022-04-20 20:40:04.627 T:892      INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-04-20 20:40:06.271 T:892      INFO <general>: initializing python engine.
2022-04-20 20:40:09.358 T:892     FATAL <general>: [plugin.video.vrt.nu] HTTP Error 503: Service Unavailable
2022-04-20 20:40:09.423 T:892     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 166, in programs
                                                       VRTPlayer().show_episodes_menu(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 276, in show_episodes_menu
                                                       episode_items, sort, ascending, content = self._apihelper.list_episodes(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 129, in list_episodes
                                                       episodes = self.get_episodes(program=program, season=season, category=category, feature=feature, programtype=programtype,
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 641, in get_episodes
                                                       api_pages = search_json.get('meta').get('pages').get('total')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2022-04-20 20:40:09.753 T:892      INFO <general>: Python interpreter stopped
2022-04-20 20:40:09.766 T:900      INFO <general>: Skipped 4 duplicate messages..
2022-04-20 20:40:09.766 T:900     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/dwars-door-de-lage-landen
2022-04-20 20:40:09.786 T:818     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/dwars-door-de-lage-landen) failed
2022-04-20 20:40:09.839 T:902      INFO <general>: initializing python engine.
2022-04-20 20:40:10.513 T:902   WARNING <general>: Invalid media type ""

```

**Comment by mediaminister** [comment]
Same issue: https://github.com/add-ons/plugin.video.vrt.nu/issues/947
