### ISSUE TITLE
Crash when selecting channels

### ISSUE THREAD

**Issue by ghen2** [add-ons/plugin.video.vrt.nu#975]
### Describe the bug ###

As of today, the vrt.nu add-on crashes when selecting channels.

### To Reproduce ###
* Open plugin
* Kies "kanalen"
* Selecteer een willekeurig kanaal
* Error (+ python backtrace in log, see below)

Idem na droppen van caches.

### Additional context ###

- Operating system: Arch Linux
- Kodi version: 19.4
- Addon version: 2.5.10+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```
2022-05-09 21:01:23.035 T:1542     INFO <general>: initializing python engine.
2022-05-09 21:01:23.039 T:1542  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/channels/een
2022-05-09 21:01:23.045 T:1542  WARNING <general>: [plugin.video.vrt.nu] Got item from cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginat.tkn'
2022-05-09 21:01:23.046 T:1542  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu-api/rest/lists/vrtnu-favoritePrograms?tileType=program-poster&tileContentType=program&tileOrientation=portrait&layout=slider&title=Mijn+favoriete+programma's
2022-05-09 21:01:23.272 T:1542  WARNING <general>: [plugin.video.vrt.nu] Write cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/favorites.json'.
2022-05-09 21:01:23.273 T:1542  WARNING <general>: [plugin.video.vrt.nu] Got item from cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginat.tkn'
2022-05-09 21:01:23.274 T:1542  WARNING <general>: [plugin.video.vrt.nu] URL get: https://ddt.profiel.vrt.be/resumePoints?max=500&sortBy=-updated
2022-05-09 21:01:23.607 T:1542  WARNING <general>: [plugin.video.vrt.nu] Write cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/resume_points.json'.
2022-05-09 21:01:23.608 T:1542  WARNING <general>: [plugin.video.vrt.nu] Got item from cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginat.tkn'
2022-05-09 21:01:23.610 T:1542  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu-api/rest/lists/vrtnu-watchLater?tileType=mixed-content&tileContentType=episode&tileOrientation=landscape&layout=slider&title=Later+kijken
2022-05-09 21:01:23.839 T:1542  WARNING <general>: [plugin.video.vrt.nu] Write cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/watchlater.json'.
2022-05-09 21:01:23.847 T:1542  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/bin/epg/schedule.2022-05-09.json
2022-05-09 21:01:23.991 T:1542  WARNING <general>: [plugin.video.vrt.nu] Write cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/schedule.today.json'.
2022-05-09 21:01:24.022 T:1542    FATAL <general>: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtnu-static/screenshots/een.jpg not found in texture cache
2022-05-09 21:01:24.023 T:1542  WARNING <general>: [plugin.video.vrt.nu] Got item from cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/schedule.today.json'
2022-05-09 21:01:24.063 T:1542  WARNING <general>: Skipped 1 duplicate messages..
2022-05-09 21:01:24.063 T:1542  WARNING <general>: [plugin.video.vrt.nu] URL get: https://search7.vrt.be/suggest?facets[programBrands]=een
2022-05-09 21:01:24.254 T:1542  WARNING <general>: [plugin.video.vrt.nu] URL get: https://search7.vrt.be/search?i=video&size=300&facets[transcodingStatus]=[AVAILABLE]&facets[episodeNumber]=[0,1]&facets[programType]=oneoff
2022-05-09 21:01:24.382 T:1542  WARNING <general>: [plugin.video.vrt.nu] Write cache '/data/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/oneoff.json'.
2022-05-09 21:01:24.391 T:1542    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'NoneType' and 'int'
                                                   Traceback (most recent call last):
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 369, in run
                                                       plugin.run(argv)
                                                     File "/data/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/data/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 184, in channels
                                                       VRTPlayer().show_channels_menu(channel=channel)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 230, in show_channels_menu
                                                       channel_items.extend(self._apihelper.list_tvshows(channel=channel))  # TV shows
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 78, in list_tvshows
                                                       oneoffs = self.get_episodes(variety='oneoff', cache_file=cache_file)
                                                     File "/data/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 647, in get_episodes
                                                       if all_items and total_results > api_page_size:
                                                   TypeError: '>' not supported between instances of 'NoneType' and 'int'
                                                   -->End of Python script error report<--
                                                   
2022-05-09 21:01:24.419 T:1542     INFO <general>: Python interpreter stopped
2022-05-09 21:01:24.429 T:1546    ERROR <general>: Skipped 2 duplicate messages..
2022-05-09 21:01:24.429 T:1546    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/channels/een
2022-05-09 21:01:24.444 T:1425    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/channels/een) failed
2022-05-09 21:01:24.464 T:1548     INFO <general>: initializing python engine.
2022-05-09 21:01:24.535 T:1548  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/channels
2022-05-09 21:01:24.546 T:1548     INFO <general>: CPythonInvoker(15, /data/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2022-05-09 21:01:24.562 T:1541    ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Podium 19.png
2022-05-09 21:01:24.562 T:1541    ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/VRT NU.png
2022-05-09 21:01:24.563 T:1541    ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/De Warmste Week.png


```

**Comment by mediaminister** [comment]
The 15dfd07 zips should work. I initially uploaded a wrong zip.

**Comment by K-Ray** [comment]
is there an official update coming for this issue or do you I have to download a specific fix?

**Comment by mediaminister** [comment]
I'll make a release next week.

**Comment by peno64** [comment]
@mediaminister 
Great work. I posted it in the vrt nu facebook group that you solved the issue. People confrm it and are glad that the addon is working  again.

**Comment by mediaminister** [comment]
Thanks, there are more issues to solve though. Not everything is working...
