### ISSUE TITLE
Error when opening La théorie du y

### ISSUE THREAD

**Issue by maanwater** [add-ons/plugin.video.vrt.nu#988]
### Describe the bug ###
When trying to open "La théorie du y" on VRT NU, an error is shown

### To Reproduce ###
1. Go to all programs
2. Scroll down to "La théorie du y"

### Expected behavior ###
See the available seasons and episodes

### Additional context ###

- Operating system: Libreelec 10.0.2
- Kodi version: 19.4
- Addon version: 2.5.11
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below
2022-05-23 21:21:12.939 T:1422  WARNING <general>: [plugin.video.vrt.nu] URL get: https://search7.vrt.be/search?i=video&size=300&available=true&orderBy=episodeId&order=desc&q=la theorie du y
2022-05-23 21:21:13.271 T:1422  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu/a-z/la-theorie-du-y.model.json
2022-05-23 21:21:13.458 T:1422    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: Cannot choose from an empty sequence
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                       plugin.run(argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 166, in programs
                                                       VRTPlayer().show_episodes_menu(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 276, in show_episodes_menu
                                                       episode_items, sort, ascending, content = self._apihelper.list_episodes(program=program, season=season)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 141, in list_episodes
                                                       return self.__map_seasons(program, seasons, episodes)
                                                     File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 182, in __map_seasons
                                                       episode = random.choice(episodes)
                                                     File "/usr/lib/python3.8/random.py", line 290, in choice
                                                   IndexError: Cannot choose from an empty sequence
                                                   -->End of Python script error report<--
                                                   
2022-05-23 21:21:14.793 T:1422     INFO <general>: Python interpreter stopped
2022-05-23 21:21:14.798 T:1446     INFO <general>: Skipped 2 duplicate messages..
2022-05-23 21:21:14.798 T:1446    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/la-theorie-du-y
2022-05-23 21:21:14.817 T:852     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/la-theorie-du-y) failed

```

**Comment by mediaminister** [comment]
Thanks for reporting. I fixed it.

Can you please test?
Fix for Kodi 18 Leia: [plugin.video.vrt.nu-2.5.11-api-015d0a4.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8765004/plugin.video.vrt.nu-2.5.11-api-015d0a4.zip)
Fix for Kodi 19 Matrix[plugin.video.vrt.nu-2.5.11+matrix.1-api-015d0a4.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8765005/plugin.video.vrt.nu-2.5.11%2Bmatrix.1-api-015d0a4.zip)

**Comment by maanwater** [comment]
Yes, the update resolves the issue. Thank you for the quick fix!

**Comment by mediaminister** [comment]
I'll release this.

**Comment by david63236** [comment]
I confirm, it's also working on Android TV.
